r"""
Scripts/generate/BakeShippingHostDefaults.py

커밋된 Engine/Game 런타임 JSON 설정을 읽어 Shipping 빌드 및 폴백용 C++ 헤더(ShippingHostDefaults.h)로 베이킹합니다.

사용법:
  python Scripts/generate/BakeShippingHostDefaults.py <output_header_path>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import (
    getProjectRoot,
    kFileRuntimeEngineConfig,
    kFileRuntimeGameConfig,
)


def escapeRawStringInternal(text: str) -> str:
    """JSON 문자열을 C++ raw string literal로 이스케이프합니다."""
    delimiter = "swcfg"
    while f"){delimiter}\"" in text:
        delimiter += "x"
    return f'R"{delimiter}({text}){delimiter}"'


def bakeShippingHostDefaults(outputPath: Path) -> int:
    """
    엔진 및 게임 런타임 JSON 설정을 읽어 C++ 헤더(ShippingHostDefaults.h)를 생성합니다.
    """
    projectRoot = getProjectRoot()
    enginePath = projectRoot / kFileRuntimeEngineConfig
    gamePath = projectRoot / kFileRuntimeGameConfig

    engineJson = "{}"
    gameJson = "{}"
    if enginePath.is_file():
        engineJson = enginePath.read_text(encoding="utf-8").strip()
        json.loads(engineJson)  # 유효성 검증
    if gamePath.is_file():
        gameJson = gamePath.read_text(encoding="utf-8").strip()
        json.loads(gameJson)

    content = f"""#pragma once
// AUTO-GENERATED by BakeShippingHostDefaults.py — do not edit.
// SSOT: committed {kFileRuntimeEngineConfig} + {kFileRuntimeGameConfig}

namespace sw::shipping_host
{{
	inline constexpr const char* kEngineConfigJson = {escapeRawStringInternal(engineJson)};
	inline constexpr const char* kGameConfigJson = {escapeRawStringInternal(gameJson)};
}}
"""

    outputPath.parent.mkdir(parents=True, exist_ok=True)
    if outputPath.exists() and outputPath.read_text(encoding="utf-8") == content:
        return 0
    outputPath.write_text(content, encoding="utf-8")
    print(f"[BakeShippingHostDefaults] Wrote {outputPath}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else list(argv)
    if len(args) < 1:
        print("Usage: BakeShippingHostDefaults.py <output_header>")
        return 1

    outputPath = Path(args[0])
    return bakeShippingHostDefaults(outputPath)


if __name__ == "__main__":
    raise SystemExit(main())
