"""
Scripts/generate/GenerateCookContract.py

Config/Engine/CookContract.json(쿠킹 표의 단일 출처)을 읽어 C++ 헤더(sw/config/CookContract.gen.h)를 생성합니다.

생성물은 X-macro 둘이다 — `SW_RHI_BACKEND_TABLE( X )` 와 `SW_COOK_SUFFIX_TABLE( X )`. 쓰는 쪽(ArgumentList.xxx ·
RHIBackendUtil · ShaderCooker · AssetCookPath)이 X 를 정의해 펼치므로, 줄이 늘면 그 자리들이 같이 늘어난다. Python 쿠커
(CookAssets.py)는 같은 파일을 `CookContractSpec` 으로 읽는다.

Usage:
  python Scripts/generate/GenerateCookContract.py <output_header_path>
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import CookContractSpec, getProjectRoot, kCookContractConfigRelative


def emitMacroInternal(macroName: str, listRow: list[str]) -> str:
    """`#define NAME( X ) \\` 와 줄마다 `X( ... )` 를 이어 붙인 X-macro 정의를 만듭니다."""
    lines = [f"#define {macroName}( X ) \\"]
    for rowIndex, row in enumerate(listRow):
        continuation = " \\" if rowIndex + 1 < len(listRow) else ""
        lines.append(f"    X( {row} ){continuation}")
    return "\n".join(lines)


def makeHeaderText(spec: CookContractSpec) -> str:
    """생성 헤더의 전체 글입니다."""
    listBackendRow = [
        ", ".join(
            [backend.name, f'"{backend.shaderFolder}"', backend.shaderTarget, backend.commandLineArgument]
            + [f'"{alias}"' for alias in backend.listAlias]
        )
        for backend in spec.listBackend
    ]
    listSuffixRow = [
        f'"{suffix.source}", "{suffix.cooked}", {suffix.kind}, {"true" if suffix.bAuthoringSource else "false"}'
        for suffix in spec.listCookSuffix
    ]
    listExclusionRow = [
        f'{target}, {kindName}, "{extension}", ""'
        for target, listKind in spec.mapExcludedKindByTarget.items()
        for kindName in listKind
        for kind in spec.listAssetKind if kind.name == kindName
        for extension in kind.listExtension
    ] + [
        f'{target}, {kindName}, "", "{folder}"'
        for target, listKind in spec.mapExcludedKindByTarget.items()
        for kindName in listKind
        for kind in spec.listAssetKind if kind.name == kindName
        for folder in kind.listFolder
    ]
    return f"""#pragma once
// AUTO-GENERATED by Scripts/generate/GenerateCookContract.py — do not edit.
// SSOT: {kCookContractConfigRelative}
//
// 쿠킹 표 둘의 C++ 쪽 표현이다. 같은 파일을 Python 쿠커(Scripts/generate/CookAssets.py)가 읽는다.

/**
 * @brief RHI 백엔드 표입니다. 줄 순서 = RHIBackend 열거값입니다.
 * @details X( Backend, ShaderFolder, ShaderTarget, CommandLineArgument, aliases... )
 *          Backend = RHIBackend 열거자, ShaderFolder = 셰이더 바이너리 폴더 이름, ShaderTarget = ShaderTargetFormat 열거자,
 *          CommandLineArgument = CommandLineArgument 열거자, aliases = 명령줄 · 셰이더 폴더 · 쿠커가 받는 이름(소문자 문자열).
 */
{emitMacroInternal("SW_RHI_BACKEND_TABLE", listBackendRow)}

/** @brief 명령줄 · 설정이 백엔드를 고르지 않았을 때 쓰는 RHIBackend 열거자입니다. */
#define SW_RHI_BACKEND_DEFAULT {spec.defaultBackend.name}

/**
 * @brief 쿡 접미사 표입니다. 긴 접미사가 먼저입니다(`.scene.xml` 이 `.scene` 보다 먼저 맞아야 한다).
 * @details X( SourceSuffix, CookedSuffix, Kind, bAuthoringSource ) — Kind = AssetKind 열거자,
 *          bAuthoringSource = 쿠커가 쿠킹하는 저작 소스인가.
 */
{emitMacroInternal("SW_COOK_SUFFIX_TABLE", listSuffixRow)}

/**
 * @brief 빌드 타깃이 패키지에서 빼고 런타임이 읽지 않는 에셋 종류입니다(`target_excluded_asset_kinds` × `asset_kinds`).
 * @details X( Target, Kind, Extension, Folder ) — Target = 빌드 타깃 이름(`Server`), Kind = 종류 이름, Extension = 소문자 확장자(`.dds`) 또는 "",
 *          Folder = 경로 조각(`shaders/bin` — 그 폴더 아래 전부) 또는 "". 한 줄에 둘 중 하나만 있다.
 */
{emitMacroInternal("SW_TARGET_ASSET_EXCLUSION_TABLE", listExclusionRow)}
"""


def generateCookContractHeader(outputPath: Path) -> int:
    try:
        spec = CookContractSpec.load(getProjectRoot())
    except (FileNotFoundError, KeyError, ValueError) as exception:
        sys.stderr.write(f"[Error] {kCookContractConfigRelative}: {exception}\n")
        return 1

    content = makeHeaderText(spec)
    outputPath.parent.mkdir(parents=True, exist_ok=True)
    previous = outputPath.read_text(encoding="utf-8") if outputPath.is_file() else ""
    if previous != content:
        outputPath.write_text(content, encoding="utf-8")
        print(f"[GenerateCookContract] Wrote {outputPath}")
    else:
        print(f"[GenerateCookContract] Up to date: {outputPath}")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) != 1:
        sys.stderr.write("Usage: GenerateCookContract.py <output_header_path>\n")
        return 1
    return generateCookContractHeader(Path(args[0]))


if __name__ == "__main__":
    raise SystemExit(main())
