r"""
Scripts/generate/GenerateShippingHostDefaults.py

커밋된 엔진 설정과 활성 게임의 프리셋(Config/Game/<게임>.json)을 읽어 Shipping 빌드 및 폴백용 C++ 헤더(ShippingHostDefaults.h)로 생성합니다.

사용법:
  python Scripts/generate/GenerateShippingHostDefaults.py <output_header_path> <game_preset_path>
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import GeneratorError, getProjectRoot, kFileRuntimeEngineConfig, runGenerator, writeGeneratedFile  # noqa: E402

kTag = "GenerateShippingHostDefaults"


def escapeRawStringInternal(text: str) -> str:
    """JSON 문자열을 C++ raw string literal로 이스케이프합니다."""
    delimiter = "swcfg"
    while f"){delimiter}\"" in text:
        delimiter += "x"
    return f'R"{delimiter}({text}){delimiter}"'


def generateShippingHostDefaults(outputPath: Path, gamePresetPath: str) -> None:
    """
    엔진 설정과 게임 프리셋을 읽어 C++ 헤더(ShippingHostDefaults.h)를 생성합니다.
    """
    projectRoot = getProjectRoot()
    enginePath = projectRoot / kFileRuntimeEngineConfig
    gamePath = projectRoot / gamePresetPath

    if not enginePath.is_file():
        raise GeneratorError(f"Engine config file not found: {enginePath}")
    if not gamePath.is_file():
        raise GeneratorError(f"Game config file not found: {gamePath}")

    try:
        engineJson = enginePath.read_text(encoding="utf-8").strip()
        json.loads(engineJson)  # 유효성 검증
    except (OSError, ValueError) as exception:
        raise GeneratorError(f"Failed to parse engine config {enginePath}: {exception}") from exception

    try:
        gameJson = gamePath.read_text(encoding="utf-8").strip()
        json.loads(gameJson)
    except (OSError, ValueError) as exception:
        raise GeneratorError(f"Failed to parse game config {gamePath}: {exception}") from exception

    content = f"""#pragma once
// AUTO-GENERATED by GenerateShippingHostDefaults.py — do not edit.
// SSOT: committed {kFileRuntimeEngineConfig} + {gamePresetPath}

namespace sw::shipping_host
{{
	inline constexpr const char* kEngineConfigJSON = {escapeRawStringInternal(engineJson)};
	inline constexpr const char* kGameConfigJSON = {escapeRawStringInternal(gameJson)};
}}
"""

    writeGeneratedFile(outputPath, content, tag=kTag, bReportUnchanged=False)


def main(argv: Sequence[str] | None = None) -> int:
    def addArgumentsInternal(parser: argparse.ArgumentParser) -> None:
        parser.add_argument("output", type=Path, help="쓸 헤더")
        parser.add_argument("gamePreset", help="게임 프리셋(저장소 기준 — Config/Game/<게임>.json)")

    return runGenerator(argv, tag=kTag, description="엔진 설정 + 게임 프리셋 → Shipping 기본값 C++ 헤더",
                        addArguments=addArgumentsInternal,
                        generate=lambda args: generateShippingHostDefaults(args.output, args.gamePreset))


if __name__ == "__main__":
    sys.exit(main())
