#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scripts/generate/GenerateLintTargets.py

`Scripts/lint/gate/` · `Scripts/lint/selftest/` 에 무엇이 있는지 보고, CMake 가 그대로
`include()` 할 린트 타깃·CTest 등록 파일(LintTargets.cmake)을 만듭니다.

**왜 CMake 가 아니라 여기인가.** 린트마다 타깃 · CTest 등록은 같은 모양이고 다른 것은 이름 · 설명 · 타임아웃뿐이다.
CMake 에 손으로 적으면 게이트 하나를 더할 때 등록 블록 · 경로 상수 · 생성 상수까지 여러 곳을 고쳐야 하고, 그것들은
전부 "`gate/` 에 놓으면 그것이 게이트다" 에서 기계적으로 유도된다. 그래서 폴더가 목록이고, 린트마다 다른 값은
린트 자신이 든다(`Scripts/lint/LintCatalog.py`).

이 저장소가 이미 `Constants.py` → `ConfigVars.cmake` 로 하고 있는 방식과 같다: **파이썬이 알고,
CMake 는 결과를 읽는다.**

Usage:
  python Scripts/generate/GenerateLintTargets.py <output_cmake_file>
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "lint"))

from common import GeneratorError, runGenerator, writeGeneratedFile  # noqa: E402
from LintCatalog import LintTarget, discoverLintTargets  # noqa: E402

kTag = "GenerateLintTargets"

kHeader = """# ==============================================================================
# AUTO-GENERATED by Scripts/generate/GenerateLintTargets.py — do not edit.
#
# 목록의 출처는 `Scripts/lint/gate/` 와 `Scripts/lint/selftest/` 폴더 그 자체이고,
# 린트마다 다른 값(설명·타임아웃·추가 인자)은 각 린트가 직접 든다:
#   `LintGate` 하위 클래스(게이트 · 셀프테스트)의 buildComment / timeoutSeconds / listCtestArgument
# 새 린트는 폴더에 파일을 놓는 것으로 끝난다 — 이 파일도, CMake 도 고칠 것이 없다.
# ==============================================================================
"""


def quoteArgumentInternal(argument: str) -> str:
    """CMake 인자 하나를 따옴표로 감쌉니다 (플래그는 그대로 — 기존 CMake 철자와 같게)."""
    return argument if argument.startswith("-") else f'"{argument}"'


def emitTargetsInternal(listTarget: Sequence[LintTarget]) -> str:
    """`sw_addRepoPythonTarget` 호출들 — `cmake --build --target CheckXxx` 로 쓰는 그것."""
    listLine: list[str] = [
        "# 린트를 따로 돌릴 수 있는 커스텀 타깃 (`cmake --build <dir> --target CheckXxx`)",
        "function(sw_addGeneratedLintTargets)",
    ]
    for target in listTarget:
        listArgument = " ".join(quoteArgumentInternal(argument) for argument in target.listCtestArgument)
        listLine.append(f'\tsw_addRepoPythonTarget({target.name} "{target.scriptRelPath}"')
        listLine.append(f'\t\tCOMMENT "{target.buildComment}"')
        listLine.append(f'\t\tARGS --root "${{CMAKE_SOURCE_DIR}}"{" " + listArgument if listArgument else ""}')
        listLine.append("\t)")
    listLine.append("endfunction()")
    return "\n".join(listLine)


def emitTestsInternal(listTarget: Sequence[LintTarget]) -> str:
    """CTest 등록 — 라벨은 전부 `lint` 다 (폴더가 성격을 말한다, CLAUDE.md)."""
    listLine: list[str] = [
        "# CTest 등록. `--fix` 같은 고치는 인자는 주지 않는다 — 게이트는 보고만 한다.",
        "function(sw_registerGeneratedLintTests)",
    ]
    for target in listTarget:
        listArgument = " ".join(quoteArgumentInternal(argument) for argument in target.listCtestArgument)
        listLine.append(f"\tif(TARGET {target.name})")
        listLine.append(f"\t\tsw_registerScriptTest({target.name}")
        listLine.append(f'\t\t\tSCRIPT "{target.scriptRelPath}"')
        listLine.append(f'\t\t\tARGS --root "${{CMAKE_SOURCE_DIR}}"{" " + listArgument if listArgument else ""}')
        listLine.append(f'\t\t\tLABELS "lint" TIMEOUT {target.timeoutSeconds})')
        listLine.append("\tendif()")
    listLine.append("endfunction()")
    return "\n".join(listLine)


def generateLintTargets(outputPath: Path) -> None:
    try:
        listTarget = discoverLintTargets()
    except ValueError as exception:
        # 트레이스백 대신 한 줄로 말한다 — 이 스크립트는 configure 단계에서 돌고,
        # 여기서 죽으면 빌드가 통째로 선다. 무엇을 고쳐야 하는지가 먼저 보여야 한다.
        raise GeneratorError(str(exception)) from exception
    if not listTarget:
        raise GeneratorError("린트를 하나도 찾지 못했습니다 — 폴더 경로를 확인하세요.")

    content = "\n".join((kHeader, emitTargetsInternal(listTarget), "", emitTestsInternal(listTarget), ""))
    writeGeneratedFile(outputPath, content, tag=kTag, summary=f"{len(listTarget)} lints")


def main(argv: Sequence[str] | None = None) -> int:
    return runGenerator(argv, tag=kTag, description="lint/gate · selftest 폴더 → CMake 린트 타깃 · 시험",
                        addArguments=lambda parser: parser.add_argument("output", type=Path, help="쓸 .cmake 파일"),
                        generate=lambda args: generateLintTargets(args.output))


if __name__ == "__main__":
    sys.exit(main())
