#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scripts/generate/GenerateToolchainCMake.py

`Config/Environment/toolchain_config.json` 을 CMake 가 바로 읽을 수 있는 `set()` 목록으로 찍습니다.

**왜 CMake 가 JSON 을 직접 파싱하지 않나.** 이 JSON 은 `SetupEnvironment.py` 가 **쓰는** 파일이다. CMake 여러 곳이
각자 파싱하면 같은 키를 상수와 리터럴 두 가지로 적게 되고, 한쪽만 바뀌는 날이 온다. 쓰는 쪽이 파이썬이니 **읽는 모양도
파이썬이 준다** — 이 저장소가 `Constants.py` → `ConfigVars.cmake` · 린트 목록 → `LintTargets.cmake`
로 하고 있는 것과 같다.

**키 목록을 여기서도 들지 않는다** — JSON 에 있는 키를 그대로 `SW_TOOLCHAIN_<KEY 대문자>` 로 찍는다.
`SetupEnvironment.py` 가 키를 하나 더하면 CMake 에서 바로 쓸 수 있다.

(`FindLlvmBin.cmake` 와 `VcpkgPortsToolchain.cmake` 는 그대로 둔다 — 그 둘은 vcpkg 가 **별도 CMake
프로세스**로 불러서 우리 빌드 디렉터리가 없는 상태에서도 성립해야 한다. 그래서 후보 루트를 거슬러
올라가며 JSON 을 직접 찾는 코드가 거기 있는 것이다.)

Usage:
  python Scripts/generate/GenerateToolchainCMake.py <output_cmake_file>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import (GeneratorError, formatCMakeSet, getProjectRoot, kDirConfigEnv, kFileToolchainConfig, runGenerator,  # noqa: E402
                    writeGeneratedFile)

kTag = "GenerateToolchainCMake"

kHeader = """# ==============================================================================
# AUTO-GENERATED by Scripts/generate/GenerateToolchainCMake.py — do not edit.
# SSOT: {relPath}  (SetupEnvironment.py 가 쓰는 파일)
#
# JSON 의 키가 그대로 SW_TOOLCHAIN_<대문자> 변수가 된다. 없는 키는 변수도 없다 —
# CMake 에서 정의되지 않은 변수는 빈 값이므로 `if(X AND EXISTS "${{X}}")` 가 그대로 동작한다.
# ==============================================================================
"""


def toCMakeNameInternal(key: str) -> str:
    """JSON 키를 CMake 변수 이름으로. `llvm_path` → `SW_TOOLCHAIN_LLVM_PATH`."""
    return "SW_TOOLCHAIN_" + key.upper()


def generateToolchainCMake(outputPath: Path, projectRoot: Path | None = None) -> None:
    root = (projectRoot or getProjectRoot()).resolve()
    relPath = f"{kDirConfigEnv}/{kFileToolchainConfig}"
    configPath = root / relPath

    listLine: list[str] = [kHeader.format(relPath=relPath)]

    if not configPath.is_file():
        # 없는 것도 답이다 — SetupEnvironment 가 아직 안 돌았거나 도구를 못 찾은 상태다.
        # CMake 쪽 폴백(find_program 등)이 그대로 동작하도록 변수를 하나도 만들지 않는다.
        listLine += ["set(SW_TOOLCHAIN_CONFIG_FOUND FALSE)", ""]
        writeGeneratedFile(outputPath, "\n".join(listLine), tag=kTag, summary=f"{relPath} 없음 — 빈 변수 파일")
        return

    try:
        mapConfig = json.loads(configPath.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exception:
        raise GeneratorError(f"{relPath} 을 읽지 못했습니다: {exception}") from exception

    listLine.append("set(SW_TOOLCHAIN_CONFIG_FOUND TRUE)")
    listLine += [formatCMakeSet(toCMakeNameInternal(key), mapConfig[key]) for key in sorted(mapConfig)]
    listLine.append("")
    writeGeneratedFile(outputPath, "\n".join(listLine), tag=kTag, summary=f"{len(mapConfig)} keys")


def main(argv: Sequence[str] | None = None) -> int:
    return runGenerator(argv, tag=kTag, description="toolchain_config.json → CMake set() 목록",
                        addArguments=lambda parser: parser.add_argument("output", type=Path, help="쓸 .cmake 파일"),
                        generate=lambda args: generateToolchainCMake(args.output))


if __name__ == "__main__":
    sys.exit(main())
