"""
Scripts/generate/GenerateCookContract.py

Config/Engine/CookContract.json(쿠킹 표의 단일 출처)을 읽어 C++ 헤더(sw/config/CookContract.gen.h)를 생성합니다.

생성물은 X-macro 둘이다 — `SW_RHI_BACKEND_TABLE( X )` 와 `SW_COOK_SUFFIX_TABLE( X )`. 쓰는 쪽(ArgumentList.xxx ·
RHIBackendUtil · ShaderCooker · AssetCookPath)이 X 를 정의해 펼치므로, 줄이 늘면 그 자리들이 같이 늘어난다. Python 쿠커
(CookAssets.py)는 같은 파일을 `CookContractSpec` 으로 읽는다.

Usage:
  python Scripts/generate/GenerateCookContract.py <output_header_path> <output_cmake_path>
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import (CookContractSpec, GeneratorError, getProjectRoot, kCookContractConfigRelative, runGenerator,  # noqa: E402
                    writeGeneratedFile)

kTag = "GenerateCookContract"


def emitMacroInternal(macroName: str, listRow: list[str]) -> str:
    """`#define NAME( X ) \\` 와 줄마다 `X( ... )` 를 이어 붙인 X-macro 정의를 만듭니다."""
    lines = [f"#define {macroName}( X ) \\"]
    for rowIndex, row in enumerate(listRow):
        continuation = " \\" if rowIndex + 1 < len(listRow) else ""
        lines.append(f"    X( {row} ){continuation}")
    return "\n".join(lines)


def makeHeaderText(spec: CookContractSpec) -> str:
    """생성 헤더의 전체 글입니다."""
    listBackendRow = [
        ", ".join(
            [backend.name, f'"{backend.shaderFolder}"', backend.shaderTarget, backend.commandLineArgument]
            + [f'"{alias}"' for alias in backend.listAlias]
        )
        for backend in spec.listBackend
    ]
    listSuffixRow = [
        f'"{suffix.source}", "{suffix.cooked}", {suffix.kind}, {"true" if suffix.bAuthoringSource else "false"}'
        for suffix in spec.listCookSuffix
    ]
    listExclusionRow = [
        f'{target}, {kindName}, "{extension}", ""'
        for target, listKind in spec.mapExcludedKindByTarget.items()
        for kindName in listKind
        for kind in spec.listAssetKind if kind.name == kindName
        for extension in kind.listExtension
    ] + [
        f'{target}, {kindName}, "", "{folder}"'
        for target, listKind in spec.mapExcludedKindByTarget.items()
        for kindName in listKind
        for kind in spec.listAssetKind if kind.name == kindName
        for folder in kind.listFolder
    ]
    return f"""#pragma once
// AUTO-GENERATED by Scripts/generate/GenerateCookContract.py — do not edit.
// SSOT: {kCookContractConfigRelative}
//
// 쿠킹 표 둘의 C++ 쪽 표현이다. 같은 파일을 Python 쿠커(Scripts/generate/CookAssets.py)가 읽는다.

/**
 * @brief RHI 백엔드 표입니다. 줄 순서 = RHIBackend 열거값입니다.
 * @details X( Backend, ShaderFolder, ShaderTarget, CommandLineArgument, aliases... )
 *          Backend = RHIBackend 열거자, ShaderFolder = 셰이더 바이너리 폴더 이름, ShaderTarget = ShaderTargetFormat 열거자,
 *          CommandLineArgument = CommandLineArgument 열거자, aliases = 명령줄 · 셰이더 폴더 · 쿠커가 받는 이름(소문자 문자열).
 */
{emitMacroInternal("SW_RHI_BACKEND_TABLE", listBackendRow)}

/** @brief 명령줄 · 설정이 백엔드를 고르지 않았을 때 쓰는 RHIBackend 열거자입니다. */
#define SW_RHI_BACKEND_DEFAULT {spec.defaultBackend.name}

/**
 * @brief 쿡 접미사 표입니다. 긴 접미사가 먼저입니다(`.scene.xml` 이 `.scene` 보다 먼저 맞아야 한다).
 * @details X( SourceSuffix, CookedSuffix, Kind, bAuthoringSource ) — Kind = AssetKind 열거자,
 *          bAuthoringSource = 쿠커가 쿠킹하는 저작 소스인가.
 */
{emitMacroInternal("SW_COOK_SUFFIX_TABLE", listSuffixRow)}

/**
 * @brief 빌드 타깃이 패키지에서 빼고 런타임이 읽지 않는 에셋 종류입니다(`target_excluded_asset_kinds` × `asset_kinds`).
 * @details X( Target, Kind, Extension, Folder ) — Target = 빌드 타깃 이름(`Server`), Kind = 종류 이름, Extension = 소문자 확장자(`.dds`) 또는 "",
 *          Folder = 경로 조각(`shaders/bin` — 그 폴더 아래 전부) 또는 "". 한 줄에 둘 중 하나만 있다.
 */
{emitMacroInternal("SW_TARGET_ASSET_EXCLUSION_TABLE", listExclusionRow)}
"""


def makeCMakeText(spec: CookContractSpec) -> str:
    """CMake 가 include 하는 백엔드 표 — `SW_RHI_BACKEND_NAMES` 와 이름마다 `SW_RHI_BACKEND_<이름>_<칸>`(cmake/Engine/RhiBackends.cmake 가 쓴다)."""
    listLine = [f"# AUTO-GENERATED by Scripts/generate/GenerateCookContract.py — do not edit. SSOT: {kCookContractConfigRelative}",
                f"set(SW_RHI_BACKEND_NAMES {' '.join(backend.name for backend in spec.listBackend)})"]
    for backend in spec.listBackend:
        prefix = f"SW_RHI_BACKEND_{backend.name}"
        listLine += [f"set({prefix}_MODULE {backend.moduleName})",
                     f"set({prefix}_SOURCE_FOLDER {backend.sourceFolder})",
                     f"set({prefix}_GRAPHICS_LIBS {backend.graphicsLibs})",
                     f"set({prefix}_SHIPPING_DEFINE {backend.shippingDefine})",
                     f"set({prefix}_ALIASES {' '.join(backend.listAlias)})"]
    return "\n".join(listLine) + "\n"


def generateCookContract(headerPath: Path, cmakePath: Path) -> None:
    try:
        spec = CookContractSpec.load(getProjectRoot())
    except (FileNotFoundError, KeyError, ValueError) as exception:
        raise GeneratorError(f"{kCookContractConfigRelative}: {exception}") from exception
    writeGeneratedFile(headerPath, makeHeaderText(spec), tag=kTag)
    writeGeneratedFile(cmakePath, makeCMakeText(spec), tag=kTag)


def main(argv: list[str] | None = None) -> int:
    def addArgumentsInternal(parser) -> None:
        parser.add_argument("header", type=Path, help="쓸 C++ 헤더")
        parser.add_argument("cmake", type=Path, help="쓸 CMake 표(RHI 백엔드)")

    return runGenerator(argv, tag=kTag, description="CookContract.json → C++ X-매크로 헤더 · CMake 백엔드 표",
                        addArguments=addArgumentsInternal,
                        generate=lambda args: generateCookContract(args.header, args.cmake))


if __name__ == "__main__":
    raise SystemExit(main())
