"""
Scripts/generate/GeneratePackFormat.py

Config/Engine/PackFormat.json(.pack 바이너리 포맷의 단일 출처)을 읽어 C++ 헤더
(sw/config/PackFormat.gen.h)를 생성합니다.

생성물은 #pragma pack(1) 구조체와 함께 sizeof / offsetof static_assert 를 함께 내보내므로,
계약 파일과 C++ 이 어긋나면 **컴파일이 깨진다**. Python 쿠커(CookAssets.py)는 같은 계약을
`PackFormatSpec` 으로 읽어 struct.pack 포맷을 만들기 때문에 양쪽이 손으로 동기화될 일이 없다 —
타입 표도, 배열 표기 해석도, "필드 합계 = 선언 크기" 검증도 `Scripts/common/PackFormat.py` 한 곳이다.

Usage:
  python Scripts/generate/GeneratePackFormat.py <output_header_path>
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import PackFormatSpec, PackStruct, getProjectRoot, kPackFormatConfigRelative


def emitStructInternal(packStruct: PackStruct) -> str:
    """구조체 정의 + sizeof/offsetof static_assert 텍스트를 만듭니다."""
    lines: list[str] = []
    lines.append("    /**")
    lines.append(f"     * @struct {packStruct.name}")
    lines.append(f"     * @brief {packStruct.doc} ({packStruct.size}바이트 고정)")
    lines.append(f"     * @details {kPackFormatConfigRelative} 에서 생성됨 — 이 파일을 직접 고치지 말 것.")
    lines.append("     */")
    lines.append(f"    struct {packStruct.name}")
    lines.append("    {")

    asserts: list[str] = []
    for field in packStruct.listField:
        initializer = "{}" if field.arrayCount else "{ 0 }"
        decl = f"        {field.scalarType} {field.name}{field.arraySuffix}{initializer};"
        lines.append(f"{decl} ///< {field.doc} ({field.byteSize}B, offset {field.offset})")
        asserts.append(
            f"    static_assert( offsetof( {packStruct.name}, {field.name} ) == {field.offset},\n"
            f"                   \"{packStruct.name}::{field.name} offset이 {kPackFormatConfigRelative} 와 다릅니다\" );"
        )

    lines.append("    };")
    lines.append(
        f"    static_assert( sizeof( {packStruct.name} ) == {packStruct.size},\n"
        f"                   \"{packStruct.name} 는 정확히 {packStruct.size}바이트여야 합니다\" );"
    )
    lines.extend(asserts)
    return "\n".join(lines)


def generatePackFormatHeader(outputPath: Path) -> int:
    try:
        spec = PackFormatSpec.load(getProjectRoot())
    except (FileNotFoundError, ValueError) as exception:
        sys.stderr.write(f"[Error] {kPackFormatConfigRelative}: {exception}\n")
        return 1

    headerText = emitStructInternal(spec.header)
    entryText = emitStructInternal(spec.entry)

    def emitConstantsInternal(prefix: str, mapping: dict) -> str:
        return "\n".join(
            f"    inline constexpr uint32 k{prefix}{name} = {value};" for name, value in mapping.items()
        )

    content = f"""#pragma once
// AUTO-GENERATED by Scripts/generate/GeneratePackFormat.py — do not edit.
// SSOT: {kPackFormatConfigRelative}
//
// 이 헤더는 .pack 바이너리 레이아웃의 C++ 쪽 표현이다. 같은 계약 파일을 Python 쿠커
// (Scripts/generate/CookAssets.py)가 읽어 쓰기 때문에, 계약을 바꾸면 양쪽이 동시에 따라온다.
#include "Core/Common/Types.h"

#include <cstddef>

namespace sw
{{
    /** @brief '{spec.magicText}' 매직 넘버 (리틀엔디언) */
    inline constexpr uint32 kPackMagic = 0x{spec.magic:08X};

    /** @brief 현재 지원하는 리소스 팩 바이너리 포맷 버전 */
    inline constexpr uint32 kPackFormatVersion = {spec.formatVersion};

    /** @brief DirectStorage 및 NVMe DMA 친화적 섹터 정렬 경계 */
    inline constexpr uint16 kPackSectorAlignment = {spec.sectorAlignment};

#pragma pack( push, 1 )
{headerText}

{entryText}
#pragma pack( pop )

    namespace packformat
    {{
        // 계약 파일의 코덱/암호화/플래그 값. ResourcePackTypes.h 의 enum 이 이 값들과
        // 일치하는지 static_assert 로 검사한다.
{emitConstantsInternal("Compression", spec.mapCodec)}

{emitConstantsInternal("Encryption", spec.mapEncryption)}

{emitConstantsInternal("Flag", spec.mapFlag)}
    }} // namespace packformat
}} // namespace sw
"""

    outputPath.parent.mkdir(parents=True, exist_ok=True)
    previous = outputPath.read_text(encoding="utf-8") if outputPath.is_file() else ""
    if previous != content:
        outputPath.write_text(content, encoding="utf-8")
        print(f"[GeneratePackFormat] Wrote {outputPath}")
    else:
        print(f"[GeneratePackFormat] Up to date: {outputPath}")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) != 1:
        sys.stderr.write("Usage: GeneratePackFormat.py <output_header_path>\n")
        return 1
    return generatePackFormatHeader(Path(args[0]))


if __name__ == "__main__":
    raise SystemExit(main())
