r"""
Scripts/generate/GenerateShippingHostDefaults.py

커밋된 엔진 설정과 활성 게임의 프리셋(Config/Game/<게임>.json)을 읽어 Shipping 빌드 및 폴백용 C++ 헤더(ShippingHostDefaults.h)로 생성합니다.

사용법:
  python Scripts/generate/GenerateShippingHostDefaults.py <output_header_path> <game_preset_path>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import (
    getProjectRoot,
    kFileRuntimeEngineConfig,
)


def escapeRawStringInternal(text: str) -> str:
    """JSON 문자열을 C++ raw string literal로 이스케이프합니다."""
    delimiter = "swcfg"
    while f"){delimiter}\"" in text:
        delimiter += "x"
    return f'R"{delimiter}({text}){delimiter}"'


def generateShippingHostDefaults(outputPath: Path, gamePresetPath: str) -> int:
    """
    엔진 설정과 게임 프리셋을 읽어 C++ 헤더(ShippingHostDefaults.h)를 생성합니다.
    """
    projectRoot = getProjectRoot()
    enginePath = projectRoot / kFileRuntimeEngineConfig
    gamePath = projectRoot / gamePresetPath

    if not enginePath.is_file():
        sys.stderr.write(f"[Error] Engine config file not found: {enginePath}\n")
        return 1
    if not gamePath.is_file():
        sys.stderr.write(f"[Error] Game config file not found: {gamePath}\n")
        return 1

    try:
        engineJson = enginePath.read_text(encoding="utf-8").strip()
        json.loads(engineJson)  # 유효성 검증
    except Exception as exception:
        sys.stderr.write(f"[Error] Failed to parse engine config {enginePath}: {exception}\n")
        return 1

    try:
        gameJson = gamePath.read_text(encoding="utf-8").strip()
        json.loads(gameJson)
    except Exception as exception:
        sys.stderr.write(f"[Error] Failed to parse game config {gamePath}: {exception}\n")
        return 1

    content = f"""#pragma once
// AUTO-GENERATED by GenerateShippingHostDefaults.py — do not edit.
// SSOT: committed {kFileRuntimeEngineConfig} + {gamePresetPath}

namespace sw::shipping_host
{{
	inline constexpr const char* kEngineConfigJson = {escapeRawStringInternal(engineJson)};
	inline constexpr const char* kGameConfigJson = {escapeRawStringInternal(gameJson)};
}}
"""

    outputPath.parent.mkdir(parents=True, exist_ok=True)
    if outputPath.exists() and outputPath.read_text(encoding="utf-8") == content:
        return 0
    outputPath.write_text(content, encoding="utf-8")
    print(f"[GenerateShippingHostDefaults] Wrote {outputPath}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else list(argv)
    if len(args) < 2:
        print("Usage: GenerateShippingHostDefaults.py <output_header> <game_preset>")
        return 1

    outputPath = Path(args[0])
    return generateShippingHostDefaults(outputPath, args[1])


if __name__ == "__main__":
    raise SystemExit(main())
