#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scripts/generate/GenerateCMakeConstants.py

`Scripts/common/Constants.py` 의 상수를 CMake 가 그대로 읽는 `set(SW_...)` 목록으로 찍습니다.

**목록을 여기서 들지 않는다.** `set(SW_...)` 줄을 손으로 적으면 CMake 변수 이름과 파이썬 상수 이름을 **두 번**
철자하게 되고, 어느 상수가 왜 빠졌는지 알 수 없게 된다(옆 `GenerateToolchainCMake.py` 도 같은 이유로 JSON 키를
그대로 변환해 찍는다). `Constants.py` 의 `k*` 는 **전부** 나간다. 이름은 기계적으로 바뀐다:

    kDirConfigEnv       -> SW_DIR_CONFIG_ENV
    kFileToolchainConfig -> SW_FILE_TOOLCHAIN_CONFIG
    kKeyLlvmPath        -> SW_KEY_LLVM_PATH
    kCppAllExtensions   -> SW_CPP_ALL_EXTENSIONS   (집합/튜플은 CMake 리스트가 된다)

상수를 하나 더하면 CMake 에서 바로 쓸 수 있다 — 여기 고칠 것이 없다.

**경로를 합치지 않는다.** 같은 이름은 파이썬과 CMake 에서 같은 값(파일 이름)을 뜻해야 한다. 한 상수만 디렉터리를
붙여 내보내면, 그걸 모르는 자리가 `${SW_DIR_CONFIG_ENV}/${SW_FILE_PARSER_CONFIG}` 로 **디렉터리를 두 번** 붙이고,
없는 경로를 `if(EXISTS)` 가 조용히 걸러 내 **`parser_config.json` 이 바뀌어도 리플렉션 코드젠이 다시 돌지 않는다.**
합치는 일은 합칠 줄 아는 쪽(`ConfigConstants.h.in` · 호출부)이 한다.

Usage:
  python Scripts/generate/GenerateCMakeConstants.py <output_cmake_file>
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import Constants as ConfigConstants  # noqa: E402
from common import GeneratorError, formatCMakeSet, runGenerator, writeGeneratedFile  # noqa: E402

kTag = "GenerateCMakeConstants"

kHeader = """# ==============================================================================
# AUTO-GENERATED by Scripts/generate/GenerateCMakeConstants.py — do not edit.
# SSOT: Scripts/common/Constants.py
#
# `k*` 상수가 그대로 `SW_<대문자 스네이크>` 변수가 된다. 상수를 더하면 변수도 생긴다 —
# 생성기에 적을 목록은 없다.
# ==============================================================================
"""


def toCMakeNameInternal(pythonName: str) -> str:
    """
    파이썬 상수 이름을 CMake 변수 이름으로. `kDirSourceEngine` → `SW_DIR_SOURCE_ENGINE`.

    앞의 `k` 를 떼고 낱말 경계(대문자)마다 `_` 를 넣는다.
    """
    bare = pythonName[1:] if pythonName.startswith("k") else pythonName

    listPart: list[str] = []
    current = ""
    for character in bare:
        if character.isupper() and current:
            listPart.append(current)
            current = character
        else:
            current += character
    if current:
        listPart.append(current)

    return "SW_" + "_".join(part.upper() for part in listPart)


def isExportableInternal(name: str, value: Any) -> bool:
    """
    내보낼 상수인가.

    `k` 로 시작하는 모듈 수준 이름만 본다 — import 해 온 것(`Path` 등)과 내부 헬퍼는 제외한다.
    """
    if not name.startswith("k") or len(name) < 2 or not name[1].isupper():
        return False

    return isinstance(value, (str, int, float, bool, set, frozenset, list, tuple))


def generateCMakeConstants(outputFile: Path) -> None:
    """공통 상수를 CMake `set(SW_...)` 구문으로 변환하여 지정된 파일에 저장합니다."""
    listLine: list[str] = [kHeader]

    mapExported: dict[str, str] = {}
    for name in sorted(vars(ConfigConstants)):
        value = getattr(ConfigConstants, name)
        if not isExportableInternal(name, value):
            continue

        cmakeName = toCMakeNameInternal(name)
        if cmakeName in mapExported:
            # 두 상수가 같은 CMake 이름으로 접히면 **조용히 하나가 이긴다** — 그 전에 멈춘다.
            raise GeneratorError(f"이름 충돌: '{name}' 와 '{mapExported[cmakeName]}' 가 둘 다 {cmakeName} 이 됩니다")

        mapExported[cmakeName] = name
        listLine.append(formatCMakeSet(cmakeName, value))

    listLine.append("")
    writeGeneratedFile(outputFile, "\n".join(listLine), tag=kTag, summary=f"{len(mapExported)} constants")


def main(argv: Sequence[str] | None = None) -> int:
    return runGenerator(argv, tag=kTag, description="Constants.py → CMake set() 목록",
                        addArguments=lambda parser: parser.add_argument("output", type=Path, help="쓸 .cmake 파일"),
                        generate=lambda args: generateCMakeConstants(args.output))


if __name__ == "__main__":
    sys.exit(main())
