# ==============================================================================
# @file cmake/Environment/FindWindowsTools.cmake
# @brief Windows lib.exe / mt.exe 탐색 및 clang-cl 아카이버 재바인딩 헬퍼 (캐시 최적화)
# ==============================================================================

# ------------------------------------------------------------------------------
# 1) sw_findWindowsArchiveAndMt — lib.exe(아카이버) / mt.exe 경로
#    우선순위: llvm-lib·llvm-mt → toolchain_config MSVC/SDK → Windows Kits
#    결과를 SW_CACHED_WIN_AR / SW_CACHED_WIN_MT에 캐싱하여 불필요한 디스크 I/O 방지
# ------------------------------------------------------------------------------
function(sw_findWindowsArchiveAndMt OUT_AR OUT_MT)
	if(DEFINED CACHE{SW_CACHED_WIN_AR} AND DEFINED CACHE{SW_CACHED_WIN_MT})
		set(${OUT_AR} "$CACHE{SW_CACHED_WIN_AR}" PARENT_SCOPE)
		set(${OUT_MT} "$CACHE{SW_CACHED_WIN_MT}" PARENT_SCOPE)
		return()
	endif()

	set(swAr "")
	set(swMt "")

	set(swCfgJson "")
	set(swSdkDir "")
	set(swSdkVer "")
	set(swMsvcTools "")
	foreach(candidateRoot IN ITEMS "${CMAKE_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
		get_filename_component(absRoot "${candidateRoot}" ABSOLUTE)
		set(cfgCandidate "${absRoot}/Config/Environment/toolchain_config.json")
		if(EXISTS "${cfgCandidate}")
			set(swCfgJson "${cfgCandidate}")
			file(READ "${swCfgJson}" cfgContent)
			string(JSON swSdkDir ERROR_VARIABLE e1 GET "${cfgContent}" "windows_sdk_dir")
			string(JSON swSdkVer ERROR_VARIABLE e2 GET "${cfgContent}" "windows_sdk_version")
			string(JSON swMsvcTools ERROR_VARIABLE e3 GET "${cfgContent}" "msvc_tools_dir")
			break()
		endif()
	endforeach()

	if(DEFINED ENV{LLVM_DIR} AND EXISTS "$ENV{LLVM_DIR}/bin/llvm-lib.exe")
		set(swAr "$ENV{LLVM_DIR}/bin/llvm-lib.exe")
	elseif(DEFINED ENV{LLVM_ROOT} AND EXISTS "$ENV{LLVM_ROOT}/bin/llvm-lib.exe")
		set(swAr "$ENV{LLVM_ROOT}/bin/llvm-lib.exe")
	elseif(swMsvcTools AND NOT swMsvcTools STREQUAL "")
		foreach(hostArch IN ITEMS Hostx64 Hostx86)
			foreach(targetArch IN ITEMS x64 x86)
				set(arCandidate "${swMsvcTools}/bin/${hostArch}/${targetArch}/lib.exe")
				if(EXISTS "${arCandidate}")
					set(swAr "${arCandidate}")
					break()
				endif()
			endforeach()
			if(swAr)
				break()
			endif()
		endforeach()
	endif()

	if(DEFINED ENV{LLVM_DIR} AND EXISTS "$ENV{LLVM_DIR}/bin/llvm-mt.exe")
		set(swMt "$ENV{LLVM_DIR}/bin/llvm-mt.exe")
	elseif(DEFINED ENV{LLVM_ROOT} AND EXISTS "$ENV{LLVM_ROOT}/bin/llvm-mt.exe")
		set(swMt "$ENV{LLVM_ROOT}/bin/llvm-mt.exe")
	elseif(swSdkDir AND swSdkVer AND NOT swSdkDir STREQUAL "" AND NOT swSdkVer STREQUAL "")
		foreach(arch IN ITEMS x64 x86)
			set(mtCandidate "${swSdkDir}/bin/${swSdkVer}/${arch}/mt.exe")
			if(EXISTS "${mtCandidate}")
				set(swMt "${mtCandidate}")
				break()
			endif()
		endforeach()
	endif()

	if(NOT swMt)
		foreach(kitsRoot IN ITEMS
			"C:/Program Files (x86)/Windows Kits/10"
			"C:/Program Files/Windows Kits/10"
		)
			if(NOT IS_DIRECTORY "${kitsRoot}/bin")
				continue()
			endif()
			file(GLOB sdkVerDirs LIST_DIRECTORIES true "${kitsRoot}/bin/10.*")
			list(SORT sdkVerDirs COMPARE NATURAL ORDER DESCENDING)
			foreach(verDir IN LISTS sdkVerDirs)
				foreach(arch IN ITEMS x64 x86)
					set(mtCandidate "${verDir}/${arch}/mt.exe")
					if(EXISTS "${mtCandidate}")
						set(swMt "${mtCandidate}")
						break()
					endif()
				endforeach()
				if(swMt)
					break()
				endif()
			endforeach()
			if(swMt)
				break()
			endif()
		endforeach()
	endif()

	set(SW_CACHED_WIN_AR "${swAr}" CACHE INTERNAL "Cached Windows ar tool")
	set(SW_CACHED_WIN_MT "${swMt}" CACHE INTERNAL "Cached Windows mt tool")
	set(${OUT_AR} "${swAr}" PARENT_SCOPE)
	set(${OUT_MT} "${swMt}" PARENT_SCOPE)
endfunction()

# ------------------------------------------------------------------------------
# 2) sw_bindClangClWindowsTools — project() 직후 clang-cl + Ninja 정적 아카이버 재바인딩
# ------------------------------------------------------------------------------
macro(sw_bindClangClWindowsTools)
	if(WIN32 AND CMAKE_CXX_COMPILER_ID MATCHES "Clang")
		set(swArTool "")
		if(CMAKE_AR AND NOT CMAKE_AR MATCHES "NOTFOUND" AND EXISTS "${CMAKE_AR}")
			set(swArTool "${CMAKE_AR}")
		endif()

		if(NOT swArTool)
			sw_findWindowsArchiveAndMt(swFoundAr swFoundMt)
			if(swFoundAr)
				set(swArTool "${swFoundAr}")
			endif()
			if(swFoundMt AND (NOT CMAKE_MT OR CMAKE_MT MATCHES "NOTFOUND"))
				set(CMAKE_MT "${swFoundMt}" CACHE FILEPATH "매니페스트 도구" FORCE)
			endif()
		endif()

		if(swArTool)
			set(CMAKE_AR "${swArTool}" CACHE FILEPATH "정적 라이브러리 아카이버" FORCE)
			set(CMAKE_C_COMPILER_AR "${swArTool}" CACHE FILEPATH "" FORCE)
			set(CMAKE_CXX_COMPILER_AR "${swArTool}" CACHE FILEPATH "" FORCE)

			set(CMAKE_C_CREATE_STATIC_LIBRARY "<CMAKE_AR> /nologo <LINK_FLAGS> /out:<TARGET> <OBJECTS>")
			set(CMAKE_CXX_CREATE_STATIC_LIBRARY "<CMAKE_AR> /nologo <LINK_FLAGS> /out:<TARGET> <OBJECTS>")
			set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> /nologo <LINK_FLAGS> /out:<TARGET> <OBJECTS>")
			set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> /nologo <LINK_FLAGS> /out:<TARGET> <OBJECTS>")
			set(CMAKE_C_ARCHIVE_APPEND "<CMAKE_AR> /nologo <LINK_FLAGS> /out:<TARGET> <OBJECTS>")
			set(CMAKE_CXX_ARCHIVE_APPEND "<CMAKE_AR> /nologo <LINK_FLAGS> /out:<TARGET> <OBJECTS>")
			set(CMAKE_C_ARCHIVE_FINISH "")
			set(CMAKE_CXX_ARCHIVE_FINISH "")

			message(STATUS "[FindWindowsTools] archive tool=${swArTool}")
		else()
			message(WARNING "[FindWindowsTools] lib.exe not found — static libraries may fail to link")
		endif()
	endif()
endmacro()
