# Editor panel visibility (1=open, 0=closed)
[PanelVisibility]
Hierarchy=1
Inspector=0
Global Variables Control=1
Game Toolbar=1
Game View=1
Output Log=1
Compute Test=1
Engine RHI Status & Command Line=1
Content Browser=1
Plot=0
Gizmo=0
Node Editor=0
Sequencer=0
Notify=0
Tex Inspect=0
