/**
 * @file ParserConfig.h
 * @brief parser_config.defaults.json(+ 로컬 parser_config.json)과 toolchain_config.json 에서 읽은 설정입니다.
 * @details clang 인자 · SDK 경로 · 코드젠 표식 · 모듈 규칙 · 튜닝이 여기 있습니다. 파서 실행 한 번에 한 번 읽어
 *          `ParserSession::_config` 로 내려 보냅니다. 예전에는 `ParserContext::getSharedConfig()` 라는 프로세스 전역이었고,
 *          표 넷을 싱글턴에서 세션으로 옮긴 뒤에도 이것 하나가 남아 호출부 스무 곳이 전역을 통해 이어져 있었습니다.
 */
#pragma once
#include "Engine/EngineMinimal.h"

namespace sw
{
    /** @brief parser/engine config에서 로드한 clang·경로·emit·tuning 입니다. */
    struct ParserConfig
    {
        vector<string> _listBaseArg;
        vector<string> _listForceInclude;
        string         _llvmClangRel;
        string         _clangIncludeRel;
        string         _msvcIncludeRel;
        string         _winSdkIncludeRel;
        string         _winSdkUcrtRel;
        string         _flagIncludePrefix;
        string         _flagIsystem;
        string         _flagResourceDir;
        string         _flagForceInclude;
        string         _flagFmsCompatibility;
        string         _flagFmsExtensions;
        string         _flagFmsCompatVersionPrefix;
        string         _emitCppExtension;
        string         _emitHeaderExtension;
        string         _emitTemplateExtension;
        string         _emitAutoGeneratedBanner;
        string         _emitPlaceholderMarker;
        string         _emitRegenByParserMarker;
        string         _emitGeneratedNsOpen;
        string         _emitGeneratedNsClose;
        string         _emitFlagOpsHeader;
        string         _emitFlagOpsMarker;
        string         _emitRegisterTypeMarker;
        string         _emitRegisterEnumMarker;
        /** @brief 산출물 머리말에 원본 헤더 경로를 적는 줄의 접두어 (FileHeader.tpl 의 "// Source: "). */
        string _emitSourcePathMarker;
        /** @brief 소스 경로 부분문자열 -> 모듈 이름 규칙. 위에서부터 처음 맞는 것을 씁니다. */
        struct ModuleRule
        {
            string _pathContains;
            string _module;
        };
        vector<ModuleRule> _listModuleRule;
        string             _defaultModule;
        /** @brief PROPERTY() 에 값으로 담으면 안 되는 기반 타입. 비면 static_assert 를 내보내지 않습니다. */
        vector<string> _listValueForbiddenBaseType;
        string         _valueForbiddenMessage;
        vector<string> _listComponentBaseType;
        vector<string> _listTypeStripPrefix;
        /**
         * @brief 실제로 읽은 설정 파일들입니다.
         * @details **설정도 산출물의 입력입니다.** 코드젠 표식 · 금지 타입 메시지 · 모듈 규칙이 여기서 오는데, 예전에는 증분
         *          판정이 이 파일들의 시각을 보지 않아 설정을 고쳐도 산출물이 옛 모양으로 남았습니다(CMake 는 DEPENDS 로 파서를
         *          다시 부르지만 파서가 스스로 "최신" 이라며 건너뛰었습니다).
         */
        vector<string>          _listLoadedFile;
        uint32                  _sourceLookbackBytes;
        uint8                   _bLoaded  : 1;
        [[maybe_unused]] uint8  _reserved : 7;
        [[maybe_unused]] uint16 _padding;

        ParserConfig() noexcept;

        /**
         * @brief 설정 파일을 찾아(현재 디렉터리에서 위로) 읽습니다.
         * @return clang 인자를 얻었으면 true. 없으면 파싱할 수 없습니다(코드젠 전용 모드는 기본값으로 충분합니다).
         */
        bool load();

        /**
         * @brief 기본 인자에 포함 경로와 강제 include 를 붙여 최종 clang 인자를 만듭니다.
         * @param listIncludePath 추가 include 경로 목록
         */
        vector<string> buildArgs( const vector<string>& listIncludePath ) const;
    };
} // namespace sw
