/**
 * @file ParserContext.h
 * @brief libclang CXIndex/CXTranslationUnit 래퍼 및 clang 인자 캐시
 */
#pragma once
#include "Engine/EngineMinimal.h"

#include <clang-c/Index.h>

namespace sw
{
    // ------------------------------------------------------------------------------
    // 1) parse — parser_config.defaults.json 로드 결과 (프로세스당 1회 캐시)
    // ------------------------------------------------------------------------------
    /** @brief parser/engine config에서 로드한 clang·경로·emit·tuning (프로세스당 1회 캐시) */
    struct ParserClangConfig
    {
        vector<string> _listBaseArg;
        vector<string> _listForceInclude;
        string         _llvmClangRel;
        string         _clangIncludeRel;
        string         _msvcIncludeRel;
        string         _winSdkIncludeRel;
        string         _winSdkUcrtRel;
        string         _flagIncludePrefix;
        string         _flagIsystem;
        string         _flagResourceDir;
        string         _flagForceInclude;
        string         _flagFmsCompatibility;
        string         _flagFmsExtensions;
        string         _flagFmsCompatVersionPrefix;
        string         _emitCppExtension;
        string         _emitHeaderExtension;
        string         _emitTemplateExtension;
        string         _emitAutoGeneratedBanner;
        string         _emitPlaceholderMarker;
        string         _emitRegenByParserMarker;
        string         _emitGeneratedNsOpen;
        string         _emitGeneratedNsClose;
        string         _emitFlagOpsHeader;
        string         _emitFlagOpsMarker;
        string         _emitRegisterTypeMarker;
        string         _emitRegisterEnumMarker;
        /** @brief 소스 경로 부분문자열 -> 모듈 이름 규칙. 위에서부터 처음 맞는 것을 씁니다. */
        struct ModuleRule
        {
            string _pathContains;
            string _module;
        };
        vector<ModuleRule> _listModuleRule;
        string             _defaultModule;
        /** @brief PROPERTY() 에 값으로 담으면 안 되는 기반 타입. 비면 static_assert 를 내보내지 않습니다. */
        vector<string>          _listValueForbiddenBaseType;
        string                  _valueForbiddenMessage;
        vector<string>          _listComponentBaseType;
        vector<string>          _listTypeStripPrefix;
        uint32                  _sourceLookbackBytes;
        uint8                   _bLoaded  : 1;
        [[maybe_unused]] uint8  _reserved : 7;
        [[maybe_unused]] uint16 _padding;

        ParserClangConfig() noexcept;

        /**
         * @brief clang 설정(인자)을 로드합니다.
         * @return 설정 로드 성공 여부
         */
        bool load();

        /**
         * @brief 기본 인자에 포함 경로를 붙여 최종 clang 인자를 만듭니다.
         * @param listIncludePath 추가 include 경로 목록
         * @return 생성된 최종 인자 목록
         */
        vector<string> buildArgs( const vector<string>& listIncludePath ) const;
    };

    // ------------------------------------------------------------------------------
    // 2) ParserContext — CXIndex / CXTranslationUnit 수명
    // ------------------------------------------------------------------------------
    class ParserContext
    {
    public:
        ParserContext();
        ~ParserContext();

        ParserContext( const ParserContext& )            = delete;
        ParserContext& operator=( const ParserContext& ) = delete;

        /** @brief 전역 공유 clang 설정을 초기화·로드합니다. */
        static bool ensureSharedConfig();

        /** @brief 전역 공유 clang 설정을 반환합니다. */
        static const ParserClangConfig& getSharedConfig();

        /**
         * @brief 지정 헤더를 파싱해 AST(CXTranslationUnit)를 만듭니다.
         * @param filePath 파싱할 소스(헤더) 경로
         * @param listIncludePath 추가 include 경로 목록
         * @param pUnsavedContents 있으면 CXUnsavedFile로 전달(키워드 스캔과 이중 I/O 방지)
         * @return 파싱 성공 여부
         */
        bool parse( const string& filePath, const vector<string>& listIncludePath,
                    const string* pUnsavedContents = nullptr );

        /** @brief 생성된 clang TranslationUnit을 반환합니다. */
        CXTranslationUnit getTranslationUnit() const { return _translationUnit; }

    private:
        CXIndex           _index;
        CXTranslationUnit _translationUnit;
    };
} // namespace sw
