/**
 * @file ParserContext.h
 * @brief libclang CXIndex/CXTranslationUnit 래퍼 및 clang 인자 캐시
 */
#pragma once
#include "Engine/EngineMinimal.h"

#include <clang-c/Index.h>

namespace sw
{
	// ------------------------------------------------------------------------------
	// 1) parse — parser_config.defaults.json 로드 결과 (프로세스당 1회 캐시)
	// ------------------------------------------------------------------------------
	/** @brief parser/engine config에서 로드한 clang·경로·emit·tuning (프로세스당 1회 캐시) */
	struct ParserClangConfig
	{
		vector<string> baseArgList;
		vector<string> forceIncludeList;
		bool		   bLoaded = false;

		// paths
		string llvmClangRel{ "lib/clang" };
		string clangIncludeRel{ "include" };
		string msvcIncludeRel{ "include" };
		string winSdkIncludeRel{ "Include" };
		string winSdkUcrtRel{ "ucrt" };

		// clang_flags
		string flagIncludePrefix{ "-I" };
		string flagIsystem{ "-isystem" };
		string flagResourceDir{ "-resource-dir" };
		string flagForceInclude{ "-include" };
		string flagFmsCompatibility{ "-fms-compatibility" };
		string flagFmsExtensions{ "-fms-extensions" };
		string flagFmsCompatVersionPrefix{ "-fms-compatibility-version" };

		// emit
		string emitCppExtension{ ".gen.cpp" };
		string emitHeaderExtension{ ".gen.h" };
		string emitTemplateExtension{ ".tpl" };
		string emitAutoGeneratedBanner{ "// AUTO-GENERATED -- DO NOT EDIT" };
		string emitPlaceholderMarker{ "AUTO-GENERATED placeholder" };
		string emitRegenByParserMarker{ "regenerated by ReflectionParser" };
		string emitGeneratedNsOpen{ "namespace sw::generated\n{\n" };
		string emitGeneratedNsClose{ "} // namespace sw::generated\n\n" };

		// tuning
		uint32 sourceLookbackBytes{ 512 };

		/**
		 * @brief clang 설정(인자)을 로드합니다.
		 * @return 설정 로드 성공 여부
		 */
		bool load();

		/**
		 * @brief 기본 인자에 포함 경로를 붙여 최종 clang 인자를 만듭니다.
		 * @param includePathList 추가 include 경로 목록
		 * @return 생성된 최종 인자 목록
		 */
		vector<string> buildArgs( const vector<string>& includePathList ) const;
	};

	// ------------------------------------------------------------------------------
	// 2) ParserContext — CXIndex / CXTranslationUnit 수명
	// ------------------------------------------------------------------------------
	class ParserContext
	{
	public:
		ParserContext();
		~ParserContext();

		ParserContext( const ParserContext& )			 = delete;
		ParserContext& operator=( const ParserContext& ) = delete;

		/** @brief 전역 공유 clang 설정을 초기화·로드합니다. */
		static bool ensureSharedConfig();

		/** @brief 전역 공유 clang 설정을 반환합니다. */
		static const ParserClangConfig& getSharedConfig();

		/**
		 * @brief 지정 헤더를 파싱해 AST(CXTranslationUnit)를 만듭니다.
		 * @param filePath 파싱할 소스(헤더) 경로
		 * @param includePathList 추가 include 경로 목록
		 * @param unsavedContents 있으면 CXUnsavedFile로 전달(키워드 스캔과 이중 I/O 방지)
		 * @return 파싱 성공 여부
		 */
		bool parse( const string& filePath, const vector<string>& includePathList,
					const string* unsavedContents = nullptr );

		/** @brief 생성된 clang TranslationUnit을 반환합니다. */
		CXTranslationUnit getTranslationUnit() const { return _translationUnit; }

	private:
		CXIndex			  _index;
		CXTranslationUnit _translationUnit;
	};
} // namespace sw
