import sys
from pathlib import Path

# ConfigHelper 경로 등록
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import ConfigHelper

def main():
    if len(sys.argv) < 2:
        print("Usage: python GenerateCMakeConstants.py <output_cmake_file>")
        sys.exit(1)
        
    out_file = Path(sys.argv[1])
    out_file.parent.mkdir(parents=True, exist_ok=True)
    
    # ConfigHelper의 상수들을 CMake 문법으로 변환
    content = f"""# ==============================================================================
# AUTO-GENERATED by GenerateCMakeConstants.py
# DO NOT EDIT MANUALLY!
# ==============================================================================

set(SW_DIR_CONFIG_ENV "{ConfigHelper.kDirConfigEnv}")
set(SW_FILE_TOOLCHAIN_CONFIG "{ConfigHelper.kFileToolchainConfig}")
set(SW_FILE_PARSER_CONFIG "{ConfigHelper.kDirConfigEnv}/{ConfigHelper.kFileParserConfig}")
set(SW_FILE_PARSER_DEFAULTS "{ConfigHelper.kDirConfigEnv}/{ConfigHelper.kFileParserDefaults}")
set(SW_FILE_SEARCH_PATHS "{ConfigHelper.kFileSearchPaths}")
set(SW_FILE_SEARCH_PATHS_DEFAULTS "{ConfigHelper.kFileSearchPathsDefaults}")

set(SW_DIR_TOOLS_LLVM "{ConfigHelper.kDirToolsLlvm}")
set(SW_DIR_TOOLS_REFLECTION_TEMPLATES "{ConfigHelper.kDirToolsReflectionTemplates}")

set(SW_DIR_SOURCE_ENGINE "{ConfigHelper.kDirSourceEngine}")
set(SW_DIR_SOURCE_GAMES "{ConfigHelper.kDirSourceGames}")
set(SW_DIR_SOURCE_GAMEFRAMEWORK "{ConfigHelper.kDirSourceGameFramework}")
set(SW_DIR_SOURCE_APP "{ConfigHelper.kDirSourceApp}")
set(SW_DIR_SOURCE_EDITOR "{ConfigHelper.kDirSourceEditor}")
set(SW_DIR_SOURCE_CORE "{ConfigHelper.kDirSourceCore}")

set(SW_FILE_REFLECT_BUILTINS "{ConfigHelper.kFileReflectBuiltins}")
set(SW_FILE_ANNOTATION_META "{ConfigHelper.kFileAnnotationMeta}")
set(SW_FILE_RUNTIME_ENGINE_CONFIG "{ConfigHelper.kFileRuntimeEngineConfig}")
set(SW_FILE_RUNTIME_APP_CONFIG "{ConfigHelper.kFileRuntimeAppConfig}")
set(SW_FILE_RUNTIME_EDITOR_CONFIG "{ConfigHelper.kFileRuntimeEditorConfig}")
set(SW_FILE_RUNTIME_GAME_CONFIG "{ConfigHelper.kFileRuntimeGameConfig}")
set(SW_FILE_RUNTIME_EDITOR_DATA "{ConfigHelper.kFileRuntimeEditorData}")

set(SW_FILE_TPL_BUILTIN_HEADER "{ConfigHelper.kFileTplBuiltinHeader}")
set(SW_FILE_TPL_BUILTIN_REGISTRAR "{ConfigHelper.kFileTplBuiltinRegistrar}")
set(SW_FILE_TPL_BUILTIN_FOOTER "{ConfigHelper.kFileTplBuiltinFooter}")

set(SW_SCRIPT_SETUP_VCPKG "{ConfigHelper.kScriptSetupVcpkg}")
set(SW_SCRIPT_SETUP_ENVIRONMENT "{ConfigHelper.kScriptSetupEnvironment}")
set(SW_SCRIPT_LINT_CHECK_ENGINE_LAYERS "{ConfigHelper.kScriptLintCheckEngineLayers}")
set(SW_SCRIPT_LINT_CHECK_SOURCE_GLOB "{ConfigHelper.kScriptLintCheckSourceGlob}")

set(SW_KEY_LLVM_PATH "{ConfigHelper.kKeyLlvmPath}")
set(SW_KEY_NINJA_PATH "{ConfigHelper.kKeyNinjaPath}")
set(SW_KEY_VCPKG_ROOT "{ConfigHelper.kKeyVcpkgRoot}")
set(SW_KEY_WINDOWS_SDK_DIR "{ConfigHelper.kKeyWindowsSdkDir}")
set(SW_KEY_WINDOWS_SDK_VERSION "{ConfigHelper.kKeyWindowsSdkVersion}")
set(SW_KEY_MSVC_TOOLS_DIR "{ConfigHelper.kKeyMsvcToolsDir}")
set(SW_KEY_SCCACHE_PATH "{ConfigHelper.kKeySccachePath}")

set(SW_KEY_LLVM_TOOLS_SUBDIR "{ConfigHelper.kKeyLlvmToolsSubdir}")

set(SW_TARGET_GAME_MODULE "{ConfigHelper.kTargetGameModule}")
set(SW_TARGET_EDITOR_MODULE "{ConfigHelper.kTargetEditorModule}")
"""
    
    if out_file.exists():
        if out_file.read_text(encoding="utf-8") == content:
            return

    out_file.write_text(content, encoding="utf-8")
    print(f"[GenerateCMakeConstants] Generated {out_file}")

if __name__ == "__main__":
    main()
