#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scripts/setup/GenerateToolchainCMake.py

`Config/Environment/toolchain_config.json` 을 CMake 가 바로 읽을 수 있는 `set()` 목록으로 찍습니다.

**왜 CMake 에서 여기로 옮겼나.** 이 JSON 은 `SetupEnvironment.py` 가 **쓰는** 파일인데, CMake 쪽이
그걸 다시 **파싱**하고 있었다 — 그것도 여러 곳에서, 서로 다른 철자로:

| 읽는 곳 | 키를 적는 방식 |
| --- | --- |
| `DetectToolchain.cmake` | `SW_KEY_*` 상수 일곱 + `if(jsonErr) set("")` 블록 일곱 |
| `FindWindowsTools.cmake` | **리터럴** `"windows_sdk_dir"` · `"windows_sdk_version"` · `"msvc_tools_dir"` |
| `Tools/ReflectionParser/CMakeLists.txt` | `SW_KEY_LLVM_PATH` 와 **리터럴** `"libclang_dll_path"` 섞어서 |

같은 키를 두 가지로 적고 있으면 한쪽만 바뀌는 날이 온다. 쓰는 쪽이 파이썬이니 **읽는 모양도
파이썬이 준다** — 이 저장소가 `Constants.py` → `ConfigVars.cmake` · 린트 목록 → `LintTargets.cmake`
로 하고 있는 것과 같다.

**키 목록을 여기서도 들지 않는다** — JSON 에 있는 키를 그대로 `SW_TOOLCHAIN_<KEY 대문자>` 로 찍는다.
`SetupEnvironment.py` 가 키를 하나 더하면 CMake 에서 바로 쓸 수 있다.

(`FindLlvmBin.cmake` 와 `VcpkgPortsToolchain.cmake` 는 그대로 둔다 — 그 둘은 vcpkg 가 **별도 CMake
프로세스**로 불러서 우리 빌드 디렉터리가 없는 상태에서도 성립해야 한다. 그래서 후보 루트를 거슬러
올라가며 JSON 을 직접 찾는 코드가 거기 있는 것이다.)

Usage:
  python Scripts/setup/GenerateToolchainCMake.py <output_cmake_file>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import getProjectRoot, kDirConfigEnv, kFileToolchainConfig

kHeader = """# ==============================================================================
# AUTO-GENERATED by Scripts/setup/GenerateToolchainCMake.py — do not edit.
# SSOT: {relPath}  (SetupEnvironment.py 가 쓰는 파일)
#
# JSON 의 키가 그대로 SW_TOOLCHAIN_<대문자> 변수가 된다. 없는 키는 변수도 없다 —
# CMake 에서 정의되지 않은 변수는 빈 값이므로 `if(X AND EXISTS "${{X}}")` 가 그대로 동작한다.
# ==============================================================================
"""


def toCMakeNameInternal(key: str) -> str:
    """JSON 키를 CMake 변수 이름으로. `llvm_path` → `SW_TOOLCHAIN_LLVM_PATH`."""
    return "SW_TOOLCHAIN_" + key.upper()


def toCMakeValueInternal(value: Any) -> str:
    """
    JSON 값을 CMake 문자열로. 배열은 CMake 리스트(`;` 구분)가 된다.

    역슬래시와 따옴표를 반드시 이스케이프한다 — 윈도우 경로가 `C:\\Program Files` 로 들어오면
    이스케이프 없이는 CMake 가 `\\P` 를 이스케이프 시퀀스로 읽어 조용히 다른 경로가 된다.
    """
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (list, tuple)):
        return ";".join(toCMakeValueInternal(item) for item in value)
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def generateToolchainCMake(outputPath: Path, projectRoot: Path | None = None) -> int:
    root = (projectRoot or getProjectRoot()).resolve()
    relPath = f"{kDirConfigEnv}/{kFileToolchainConfig}"
    configPath = root / relPath

    listLine: list[str] = [kHeader.format(relPath=relPath)]

    if not configPath.is_file():
        # 없는 것도 답이다 — SetupEnvironment 가 아직 안 돌았거나 도구를 못 찾은 상태다.
        # CMake 쪽 폴백(find_program 등)이 그대로 동작하도록 변수를 하나도 만들지 않는다.
        listLine.append("set(SW_TOOLCHAIN_CONFIG_FOUND FALSE)")
        listLine.append("")
        outputPath.parent.mkdir(parents=True, exist_ok=True)
        outputPath.write_text("\n".join(listLine), encoding="utf-8")
        print(f"[GenerateToolchainCMake] {relPath} 이 없습니다 — 빈 변수 파일을 썼습니다")
        return 0

    try:
        mapConfig = json.loads(configPath.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exception:
        sys.stderr.write(f"[GenerateToolchainCMake] {relPath} 을 읽지 못했습니다: {exception}\n")
        return 1

    listLine.append("set(SW_TOOLCHAIN_CONFIG_FOUND TRUE)")
    for key in sorted(mapConfig):
        listLine.append(f'set({toCMakeNameInternal(key)} "{toCMakeValueInternal(mapConfig[key])}")')
    listLine.append("")

    content = "\n".join(listLine)
    outputPath.parent.mkdir(parents=True, exist_ok=True)
    previous = outputPath.read_text(encoding="utf-8") if outputPath.is_file() else ""
    if previous != content:
        outputPath.write_text(content, encoding="utf-8")
        print(f"[GenerateToolchainCMake] Wrote {outputPath} ({len(mapConfig)} keys)")
    else:
        print(f"[GenerateToolchainCMake] Up to date: {outputPath} ({len(mapConfig)} keys)")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    listArgument = list(sys.argv[1:] if argv is None else argv)
    if len(listArgument) != 1:
        sys.stderr.write("Usage: GenerateToolchainCMake.py <output_cmake_file>\n")
        return 1
    return generateToolchainCMake(Path(listArgument[0]))


if __name__ == "__main__":
    sys.exit(main())
