#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scripts/setup/GenerateCMakeConstants.py

`Scripts/common/Constants.py` 의 상수를 CMake 가 그대로 읽는 `set(SW_...)` 목록으로 찍습니다.

**목록을 여기서 들지 않는다.** 예전에는 `set(SW_...)` 서른여섯 줄을 손으로 적어 두고, 그 줄마다
CMake 변수 이름과 파이썬 상수 이름을 **두 번** 철자했다. 상수 여든여섯 개 중 서른여섯 개만 나갔고,
어느 것이 왜 빠졌는지는 주석으로만 남아 있었다. 바로 옆 `GenerateToolchainCMake.py` 는 이미
"키 목록을 여기서도 들지 않는다" 고 적어 놓고 JSON 키를 그대로 변환해 찍는다 — 같은 문제에 같은
저장소가 두 가지 답을 들고 있었다.

이제 `Constants.py` 의 `k*` 는 **전부** 나간다. 이름은 기계적으로 바뀐다:

    kDirConfigEnv       -> SW_DIR_CONFIG_ENV
    kFileToolchainConfig -> SW_FILE_TOOLCHAIN_CONFIG
    kKeyLlvmPath        -> SW_KEY_LLVM_PATH
    kCppAllExtensions   -> SW_CPP_ALL_EXTENSIONS   (집합/튜플은 CMake 리스트가 된다)

상수를 하나 더하면 CMake 에서 바로 쓸 수 있다 — 여기 고칠 것이 없다.

**경로를 합치지 않는다.** 예전에는 `SW_FILE_PARSER_CONFIG` 만 `kDirConfigEnv` 를 앞에 붙여
내보냈다. 그래서 같은 이름이 파이썬에서는 `parser_config.json`, CMake 에서는
`Config/Environment/parser_config.json` 을 뜻했고, 그 둘이 다르다는 걸 모르는 자리에서
`${SW_DIR_CONFIG_ENV}/${SW_FILE_PARSER_CONFIG}` 로 **디렉터리를 두 번** 붙였다
(`cmake/Engine/ReflectionCodeGen.cmake`). 그 경로는 존재하지 않으니 `if(EXISTS)` 가 조용히
걸러 냈고, 결과적으로 **`parser_config.json` 이 바뀌어도 리플렉션 코드젠이 다시 돌지 않았다.**
합치는 일은 합칠 줄 아는 쪽(`ConfigConstants.h.in` · 호출부)이 한다.

Usage:
  python Scripts/setup/GenerateCMakeConstants.py <output_cmake_file>
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import Constants as ConfigConstants

kHeader = """# ==============================================================================
# AUTO-GENERATED by Scripts/setup/GenerateCMakeConstants.py — do not edit.
# SSOT: Scripts/common/Constants.py
#
# `k*` 상수가 그대로 `SW_<대문자 스네이크>` 변수가 된다. 상수를 더하면 변수도 생긴다 —
# 생성기에 적을 목록은 없다.
# ==============================================================================
"""


def toCMakeNameInternal(pythonName: str) -> str:
    """
    파이썬 상수 이름을 CMake 변수 이름으로. `kDirSourceEngine` → `SW_DIR_SOURCE_ENGINE`.

    앞의 `k` 를 떼고 낱말 경계(대문자)마다 `_` 를 넣는다.
    """
    bare = pythonName[1:] if pythonName.startswith("k") else pythonName

    listPart: list[str] = []
    current = ""
    for character in bare:
        if character.isupper() and current:
            listPart.append(current)
            current = character
        else:
            current += character
    if current:
        listPart.append(current)

    return "SW_" + "_".join(part.upper() for part in listPart)


def toCMakeValueInternal(value: Any) -> str:
    """
    값을 CMake 문자열로. 집합·튜플·리스트는 CMake 리스트(`;` 구분)가 된다.

    역슬래시와 따옴표를 이스케이프한다 — 윈도우 경로가 그대로 들어오면 CMake 가 백슬래시 뒤
    글자를 이스케이프 시퀀스로 읽어 조용히 다른 경로가 된다.
    """
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"

    if isinstance(value, (set, frozenset)):
        return ";".join(toCMakeValueInternal(item) for item in sorted(value))

    if isinstance(value, (list, tuple)):
        return ";".join(toCMakeValueInternal(item) for item in value)

    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def isExportableInternal(name: str, value: Any) -> bool:
    """
    내보낼 상수인가.

    `k` 로 시작하는 모듈 수준 이름만 본다 — import 해 온 것(`Path` 등)과 내부 헬퍼는 제외한다.
    """
    if not name.startswith("k") or len(name) < 2 or not name[1].isupper():
        return False

    return isinstance(value, (str, int, float, bool, set, frozenset, list, tuple))


def generateCMakeConstants(outputFile: Path) -> int:
    """공통 상수를 CMake `set(SW_...)` 구문으로 변환하여 지정된 파일에 저장합니다."""
    listLine: list[str] = [kHeader]

    mapExported: dict[str, str] = {}
    for name in sorted(vars(ConfigConstants)):
        value = getattr(ConfigConstants, name)
        if not isExportableInternal(name, value):
            continue

        cmakeName = toCMakeNameInternal(name)
        if cmakeName in mapExported:
            # 두 상수가 같은 CMake 이름으로 접히면 **조용히 하나가 이긴다** — 그 전에 멈춘다.
            sys.stderr.write(
                f"[GenerateCMakeConstants] 이름 충돌: '{name}' 와 '{mapExported[cmakeName]}' "
                f"가 둘 다 {cmakeName} 이 됩니다\n"
            )
            return 1

        mapExported[cmakeName] = name
        listLine.append(f'set({cmakeName} "{toCMakeValueInternal(value)}")')

    listLine.append("")
    content = "\n".join(listLine)

    outputFile.parent.mkdir(parents=True, exist_ok=True)
    previous = outputFile.read_text(encoding="utf-8") if outputFile.is_file() else ""
    if previous != content:
        outputFile.write_text(content, encoding="utf-8")
        print(f"[GenerateCMakeConstants] Wrote {outputFile} ({len(mapExported)} constants)")
    else:
        print(f"[GenerateCMakeConstants] Up to date: {outputFile} ({len(mapExported)} constants)")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    listArgument = list(sys.argv[1:] if argv is None else argv)
    if len(listArgument) != 1:
        sys.stderr.write("Usage: GenerateCMakeConstants.py <output_cmake_file>\n")
        return 1

    return generateCMakeConstants(Path(listArgument[0]))


if __name__ == "__main__":
    sys.exit(main())
