"""
Scripts/setup/GenerateCMakeConstants.py

Scripts/common/Constants.py의 프로젝트 경로 및 설정 상수를 읽어 CMake에서 인클루드할 변수 파일(ConfigVars.cmake)을 자동 생성합니다.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import Constants as ConfigConstants


def generateCMakeConstants(outputFile: Path) -> int:
    """
    공통 상수를 CMake `set(SW_...)` 구문으로 변환하여 지정된 파일에 저장합니다.
    """
    outputFile.parent.mkdir(parents=True, exist_ok=True)

    content = f"""# ==============================================================================
# AUTO-GENERATED by GenerateCMakeConstants.py
# DO NOT EDIT MANUALLY! (Single Source of Truth: Scripts/common/Constants.py)
# ==============================================================================

set(SW_DIR_CONFIG_ENV "{ConfigConstants.kDirConfigEnv}")
set(SW_FILE_TOOLCHAIN_CONFIG "{ConfigConstants.kFileToolchainConfig}")
set(SW_FILE_PARSER_CONFIG "{ConfigConstants.kDirConfigEnv}/{ConfigConstants.kFileParserConfig}")
set(SW_FILE_PARSER_DEFAULTS "{ConfigConstants.kDirConfigEnv}/{ConfigConstants.kFileParserDefaults}")
set(SW_FILE_SEARCH_PATHS "{ConfigConstants.kFileSearchPaths}")
set(SW_FILE_SEARCH_PATHS_DEFAULTS "{ConfigConstants.kFileSearchPathsDefaults}")

set(SW_DIR_TOOLS_LLVM "{ConfigConstants.kDirToolsLlvm}")
set(SW_DIR_TOOLS_REFLECTION_TEMPLATES "{ConfigConstants.kDirToolsReflectionTemplates}")

set(SW_DIR_SOURCE_ENGINE "{ConfigConstants.kDirSourceEngine}")
set(SW_DIR_SOURCE_GAMES "{ConfigConstants.kDirSourceGames}")
set(SW_DIR_SOURCE_GAMEFRAMEWORK "{ConfigConstants.kDirSourceGameFramework}")
set(SW_DIR_SOURCE_APP "{ConfigConstants.kDirSourceApp}")
set(SW_DIR_SOURCE_EDITOR "{ConfigConstants.kDirSourceEditor}")
set(SW_DIR_SOURCE_CORE "{ConfigConstants.kDirSourceCore}")

set(SW_FILE_REFLECT_BUILTINS "{ConfigConstants.kFileReflectBuiltins}")
set(SW_FILE_ANNOTATION_META "{ConfigConstants.kFileAnnotationMeta}")
set(SW_FILE_RUNTIME_ENGINE_CONFIG "{ConfigConstants.kFileRuntimeEngineConfig}")
set(SW_FILE_RUNTIME_APP_CONFIG "{ConfigConstants.kFileRuntimeAppConfig}")
set(SW_FILE_RUNTIME_EDITOR_CONFIG "{ConfigConstants.kFileRuntimeEditorConfig}")
set(SW_FILE_RUNTIME_GAME_CONFIG "{ConfigConstants.kFileRuntimeGameConfig}")
set(SW_FILE_RUNTIME_EDITOR_DATA "{ConfigConstants.kFileRuntimeEditorData}")

set(SW_FILE_TPL_BUILTIN_HEADER "{ConfigConstants.kFileTplBuiltinHeader}")
set(SW_FILE_TPL_BUILTIN_REGISTRAR "{ConfigConstants.kFileTplBuiltinRegistrar}")
set(SW_FILE_TPL_BUILTIN_FOOTER "{ConfigConstants.kFileTplBuiltinFooter}")

set(SW_SCRIPT_SETUP_VCPKG "{ConfigConstants.kScriptSetupVcpkg}")
set(SW_SCRIPT_SETUP_ENVIRONMENT "{ConfigConstants.kScriptSetupEnvironment}")
set(SW_SCRIPT_LINT_CHECK_ENGINE_LAYERS "{ConfigConstants.kScriptLintCheckEngineLayers}")
set(SW_SCRIPT_LINT_CHECK_INCLUDE_ORDER "{ConfigConstants.kScriptLintCheckIncludeOrder}")
set(SW_SCRIPT_LINT_CHECK_RESOURCE_CASING "{ConfigConstants.kScriptLintCheckResourceCasing}")
set(SW_SCRIPT_LINT_CHECK_CODE_CONVENTIONS "{ConfigConstants.kScriptLintCheckCodeConventions}")
set(SW_SCRIPT_LINT_CHECK_SOURCE_GLOB "{ConfigConstants.kScriptLintCheckSourceGlob}")
set(SW_SCRIPT_LINT_RUN_CLANG_FORMAT "{ConfigConstants.kScriptLintRunClangFormat}")
set(SW_SCRIPT_GENERATE_BAKE_SHIPPING_HOST_DEFAULTS "{ConfigConstants.kScriptGenerateBakeShippingHostDefaults}")
set(SW_SCRIPT_COOK_ASSETS "{ConfigConstants.kScriptCookAssets}")
set(SW_SCRIPT_GENERATE_DOCS "{ConfigConstants.kScriptGenerateDocs}")

set(SW_KEY_LLVM_PATH "{ConfigConstants.kKeyLlvmPath}")
set(SW_KEY_NINJA_PATH "{ConfigConstants.kKeyNinjaPath}")
set(SW_KEY_VCPKG_ROOT "{ConfigConstants.kKeyVcpkgRoot}")
set(SW_KEY_WINDOWS_SDK_DIR "{ConfigConstants.kKeyWindowsSdkDir}")
set(SW_KEY_WINDOWS_SDK_VERSION "{ConfigConstants.kKeyWindowsSdkVersion}")
set(SW_KEY_MSVC_TOOLS_DIR "{ConfigConstants.kKeyMsvcToolsDir}")
set(SW_KEY_SCCACHE_PATH "{ConfigConstants.kKeySccachePath}")

set(SW_KEY_LLVM_TOOLS_SUBDIR "{ConfigConstants.kKeyLlvmToolsSubdir}")

set(SW_TARGET_GAME_MODULE "{ConfigConstants.kTargetGameModule}")
set(SW_TARGET_EDITOR_MODULE "{ConfigConstants.kTargetEditorModule}")
"""

    if outputFile.exists() and outputFile.read_text(encoding="utf-8") == content:
        return 0

    outputFile.write_text(content, encoding="utf-8")
    print(f"[GenerateCMakeConstants] Generated {outputFile}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parsedArgs = sys.argv[1:] if argv is None else list(argv)
    if len(parsedArgs) < 1:
        print("Usage: python GenerateCMakeConstants.py <output_cmake_file>")
        return 1

    outputFile = Path(parsedArgs[0])
    return generateCMakeConstants(outputFile)


if __name__ == "__main__":
    sys.exit(main())
