#!/usr/bin/env python3
"""
Scripts/setup/InstallGitHooks.py

Git pre-commit 훅을 .git/hooks/ 디렉터리에 설치하여 커밋 시 레이어 및 GLOB 검사를 자동 수행합니다.
"""

from __future__ import annotations

import os
import platform
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import getProjectRoot


def installPreCommitHook(projectRoot: Path | None = None) -> bool:
    """
    .git/hooks/pre-commit 훅을 설치하여 커밋 시 PreCommitLint.py가 자동 실행되도록 합니다.
    """
    root = projectRoot or getProjectRoot()
    gitDir = root / ".git"

    if not gitDir.is_dir():
        return False

    hooksDir = gitDir / "hooks"
    hooksDir.mkdir(parents=True, exist_ok=True)

    preCommitPath = hooksDir / "pre-commit"
    hookScript = (
        "#!/bin/sh\n"
        "# Auto-generated by SW Engine setup\n\n"
        "if command -v py >/dev/null 2>&1; then\n"
        "  py -3 -m Scripts lint\n"
        "elif command -v python3 >/dev/null 2>&1; then\n"
        "  python3 -m Scripts lint\n"
        "elif command -v python >/dev/null 2>&1; then\n"
        "  python -m Scripts lint\n"
        "else\n"
        '  echo "[pre-commit] Error: Python was not found in PATH." >&2\n'
        "  exit 1\n"
        "fi\n\n"
        "if [ $? -ne 0 ]; then\n"
        "  exit 1\n"
        "fi\n"
    )

    preCommitPath.write_text(hookScript, encoding="utf-8")
    if platform.system() != "Windows":
        os.chmod(preCommitPath, 0o755)

    print(f"[InstallGitHooks] Git pre-commit 훅이 설치되었습니다: {preCommitPath}")
    return True


def main() -> int:
    if not installPreCommitHook():
        print("[InstallGitHooks] .git 디렉터리를 찾을 수 없습니다.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
