r"""
Bake committed Config/Engine + Config/Game JSON into a C++ header for Shipping
(and Dev fallback when disk Config is missing).

Usage:
  python Scripts/BakeShippingHostDefaults.py <output_header_path>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ConfigHelper


def escapeRawString(text: str) -> str:
	# Prefer a delimiter that does not appear in JSON.
	delim = "swcfg"
	while f"){delim}\"" in text:
		delim += "x"
	return f'R"{delim}({text}){delim}"'


def main() -> int:
	if len(sys.argv) < 2:
		print("Usage: BakeShippingHostDefaults.py <output_header>")
		return 1

	outPath = Path(sys.argv[1])
	root = ConfigHelper.getProjectRoot()
	enginePath = root / ConfigHelper.kFileRuntimeEngineConfig
	gamePath = root / ConfigHelper.kFileRuntimeGameConfig

	engineJson = "{}"
	gameJson = "{}"
	if enginePath.is_file():
		engineJson = enginePath.read_text(encoding="utf-8").strip()
		json.loads(engineJson)  # validate
	if gamePath.is_file():
		gameJson = gamePath.read_text(encoding="utf-8").strip()
		json.loads(gameJson)

	content = f"""#pragma once
// AUTO-GENERATED by BakeShippingHostDefaults.py — do not edit.
// SSOT: committed {ConfigHelper.kFileRuntimeEngineConfig} + {ConfigHelper.kFileRuntimeGameConfig}

namespace sw::shipping_host
{{
	inline constexpr const char* kEngineConfigJson = {escapeRawString(engineJson)};
	inline constexpr const char* kGameConfigJson = {escapeRawString(gameJson)};
}}
"""

	outPath.parent.mkdir(parents=True, exist_ok=True)
	if outPath.exists() and outPath.read_text(encoding="utf-8") == content:
		return 0
	outPath.write_text(content, encoding="utf-8")
	print(f"[BakeShippingHostDefaults] Wrote {outPath}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
