# ==============================================================================
# AUTO-GENERATED by GenerateCMakeConstants.py
# DO NOT EDIT MANUALLY! (Single Source of Truth: Scripts/common/Constants.py)
# ==============================================================================

set(SW_DIR_CONFIG_ENV "Config/Environment")
set(SW_FILE_TOOLCHAIN_CONFIG "toolchain_config.json")
set(SW_FILE_PARSER_CONFIG "Config/Environment/parser_config.json")
set(SW_FILE_PARSER_DEFAULTS "Config/Environment/parser_config.defaults.json")
set(SW_FILE_SEARCH_PATHS "search_paths.json")
set(SW_FILE_SEARCH_PATHS_DEFAULTS "search_paths.defaults.json")

set(SW_DIR_TOOLS_LLVM "Tools/LLVM")
set(SW_DIR_TOOLS_REFLECTION_TEMPLATES "Tools/ReflectionParser/Templates")

set(SW_DIR_SOURCE_ENGINE "Source/Engine")
set(SW_DIR_SOURCE_GAMES "Source/Games")
set(SW_DIR_SOURCE_GAMEFRAMEWORK "Source/GameFramework")
set(SW_DIR_SOURCE_APP "Source/App")
set(SW_DIR_SOURCE_EDITOR "Source/Editor")
set(SW_DIR_SOURCE_CORE "Source/Core")

set(SW_FILE_REFLECT_BUILTINS "Source/Engine/Reflection/ReflectBuiltins.xxx")
set(SW_FILE_ANNOTATION_META "Source/Core/Predefined/AnnotationMeta.txt")
set(SW_FILE_RUNTIME_ENGINE_CONFIG "Config/Engine/EngineConfig.json")
set(SW_FILE_RUNTIME_APP_CONFIG "Config/App/AppConfig.json")
set(SW_FILE_RUNTIME_EDITOR_CONFIG "Config/Editor/EditorConfig.json")
set(SW_FILE_RUNTIME_GAME_CONFIG "Config/Game/GameConfig.json")
set(SW_FILE_RUNTIME_EDITOR_DATA "Config/Editor/editordata.xml")

set(SW_FILE_TPL_BUILTIN_HEADER "BuiltinFileHeader.tpl")
set(SW_FILE_TPL_BUILTIN_REGISTRAR "BuiltinTypeRegistrar.tpl")
set(SW_FILE_TPL_BUILTIN_FOOTER "BuiltinFileFooter.tpl")

set(SW_SCRIPT_SETUP_VCPKG "Scripts/setup/SetupVcpkg.py")
set(SW_SCRIPT_SETUP_ENVIRONMENT "Scripts/setup/SetupEnvironment.py")
set(SW_SCRIPT_LINT_CHECK_ENGINE_LAYERS "Scripts/lint/CheckEngineLayers.py")
set(SW_SCRIPT_LINT_CHECK_INCLUDE_ORDER "Scripts/lint/CheckIncludeOrder.py")
set(SW_SCRIPT_LINT_CHECK_RESOURCE_CASING "Scripts/lint/CheckResourceCasing.py")
set(SW_SCRIPT_LINT_CHECK_CODE_CONVENTIONS "Scripts/lint/CheckCodeConventions.py")
set(SW_SCRIPT_LINT_CHECK_SOURCE_GLOB "Scripts/lint/CheckSourceGlob.py")
set(SW_SCRIPT_LINT_RUN_CLANG_FORMAT "Scripts/lint/RunClangFormat.py")
set(SW_SCRIPT_GENERATE_BAKE_SHIPPING_HOST_DEFAULTS "Scripts/generate/BakeShippingHostDefaults.py")
set(SW_SCRIPT_GENERATE_COOK_PREFABS "Scripts/generate/CookPrefabs.py")
set(SW_SCRIPT_GENERATE_COOK_SCENES "Scripts/generate/CookScenes.py")
set(SW_SCRIPT_GENERATE_DOCS "Scripts/generate/GenerateDocs.py")

set(SW_KEY_LLVM_PATH "llvm_path")
set(SW_KEY_NINJA_PATH "ninja_path")
set(SW_KEY_VCPKG_ROOT "vcpkg_root")
set(SW_KEY_WINDOWS_SDK_DIR "windows_sdk_dir")
set(SW_KEY_WINDOWS_SDK_VERSION "windows_sdk_version")
set(SW_KEY_MSVC_TOOLS_DIR "msvc_tools_dir")
set(SW_KEY_SCCACHE_PATH "sccache_path")

set(SW_KEY_LLVM_TOOLS_SUBDIR "llvm_tools_subdir")

set(SW_TARGET_GAME_MODULE "SWGame")
set(SW_TARGET_EDITOR_MODULE "EditorModule")
