# ==============================================================================
# @file cmake/Engine/ReflectionCodeGen.cmake
# @brief ReflectionParser로 .gen.cpp를 생성하는 CMake 코드젠 파이프라인
# ==============================================================================

# ------------------------------------------------------------------------------
# 1) sw_addReflectionStep — ENUM() 헤더 → .gen.cpp / .gen.h
#    HEADERS / INCLUDES / OUTPUT_DIR. .gen.cpp는 Unity 배치에서 제외 (ODR)
#    루트가 Tools(ReflectionParser) 이후 Engine을 호출해야 이 스텝이 살아 있음
# ------------------------------------------------------------------------------
function(sw_addReflectionStep TARGET_NAME)
    cmake_parse_arguments(ARG "" "OUTPUT_DIR" "HEADERS;INCLUDES" ${ARGN})

    if(NOT TARGET ReflectionParser)
        if(SW_REQUIRE_REFLECTION)
            message(FATAL_ERROR
                "[Reflection] ReflectionParser target missing but SW_REQUIRE_REFLECTION=ON.\n"
                "  Install LLVM/libclang (Config/Environment/toolchain_config.json llvm_path) or set -DSW_REQUIRE_REFLECTION=OFF.")

        endif()
        message(WARNING "[Reflection] ReflectionParser target not found. Skipping step for: ${TARGET_NAME}")
        return()
    endif()

    if(NOT ARG_OUTPUT_DIR)
        set(ARG_OUTPUT_DIR "${CMAKE_BINARY_DIR}/generated/${TARGET_NAME}")
    endif()

    if(NOT ARG_HEADERS)
        message(STATUS "[Reflection] No HEADERS specified for target: ${TARGET_NAME}, auto-scanning for REFLECT macros...")
        file(GLOB_RECURSE _all_headers "${CMAKE_CURRENT_SOURCE_DIR}/*.h" "${CMAKE_CURRENT_SOURCE_DIR}/*.hpp")
        foreach(_hdr IN LISTS _all_headers)
            file(STRINGS "${_hdr}" _has_reflect REGEX "^[ \t]*(REFLECT\\(|ENUM\\(|REFLECT_CONTAINER\\()")
            if(_has_reflect)
                list(APPEND ARG_HEADERS "${_hdr}")
            endif()
        endforeach()
        if(NOT ARG_HEADERS)
            message(STATUS "[Reflection] Auto-scan found no headers with REFLECT macros for target: ${TARGET_NAME}")
            return()
        endif()
    endif()

    set(parserArgs "")
    foreach(header IN LISTS ARG_HEADERS)
        list(APPEND parserArgs "--input" "${header}")
    endforeach()
    list(APPEND parserArgs "--output" "${ARG_OUTPUT_DIR}")
    set(_swReflectBuiltins "${CMAKE_SOURCE_DIR}/${SW_FILE_REFLECT_BUILTINS}")
    set(_swAnnotationMeta "${CMAKE_SOURCE_DIR}/${SW_FILE_ANNOTATION_META}")
    set(_swEmitTemplatesDir "${CMAKE_SOURCE_DIR}/${SW_DIR_TOOLS_REFLECTION_TEMPLATES}")
    list(APPEND parserArgs "--builtins" "${_swReflectBuiltins}")
    list(APPEND parserArgs "--annotation-meta" "${_swAnnotationMeta}")
    list(APPEND parserArgs "--emit-templates" "${_swEmitTemplatesDir}")
    # 모듈 판별을 소스 루트 기준 상대 경로로 하게 한다. 절대 경로로 매칭하면
    # 리포지토리를 담은 상위 폴더 이름(.../AppData/..., D:/Games/... 등)에 걸려 오분류된다.
    list(APPEND parserArgs "--source-root" "${CMAKE_SOURCE_DIR}/Source")
    file(GLOB _swEmitTpls "${_swEmitTemplatesDir}/*.tpl")
    foreach(inc IN LISTS ARG_INCLUDES)
        list(APPEND parserArgs "--include" "${inc}")
    endforeach()

    # 파서가 런타임에 읽는 설정. 바뀌면 clang 인자/SDK 경로가 달라지므로 재생성해야 함.
    set(_swParserConfigs "")
    foreach(cfg
        "${CMAKE_SOURCE_DIR}/${SW_DIR_CONFIG_ENV}/${SW_FILE_PARSER_CONFIG}"
        "${CMAKE_SOURCE_DIR}/${SW_DIR_CONFIG_ENV}/${SW_FILE_PARSER_DEFAULTS}"
        "${CMAKE_SOURCE_DIR}/${SW_DIR_CONFIG_ENV}/${SW_FILE_TOOLCHAIN_CONFIG}")
        if(EXISTS "${cfg}")
            list(APPEND _swParserConfigs "${cfg}")
        endif()
    endforeach()

    file(MAKE_DIRECTORY "${ARG_OUTPUT_DIR}")
    set(generatedFiles "")
    foreach(header IN LISTS ARG_HEADERS)
        get_filename_component(stem "${header}" NAME_WE)
        set(genFile "${ARG_OUTPUT_DIR}/${stem}.gen.cpp")
        set(genHeader "${ARG_OUTPUT_DIR}/${stem}.gen.h")
        list(APPEND generatedFiles "${genFile}" "${genHeader}")
        if(NOT EXISTS "${genFile}")
            file(WRITE "${genFile}" "// AUTO-GENERATED placeholder — regenerated by ReflectionParser\n")
        endif()
        if(NOT EXISTS "${genHeader}")
            file(WRITE "${genHeader}" "// AUTO-GENERATED placeholder\n#pragma once\n")
        endif()
    endforeach()

    set(_swFlagOpsHeader "${ARG_OUTPUT_DIR}/FlagOps.gen.h")
    list(APPEND generatedFiles "${_swFlagOpsHeader}")
    if(NOT EXISTS "${_swFlagOpsHeader}")
        file(WRITE "${_swFlagOpsHeader}" "// AUTO-GENERATED placeholder\n#pragma once\n#if !defined(__REFLECT_PARSER__)\n// no ENUM(Flags) in this target\n#endif\n")
    endif()

    add_custom_command(
        OUTPUT ${generatedFiles}
        COMMAND ${CMAKE_COMMAND} -E make_directory "${ARG_OUTPUT_DIR}"
        COMMAND "$<TARGET_FILE:ReflectionParser>" ${parserArgs}
        DEPENDS ${ARG_HEADERS} ReflectionParser "$<TARGET_FILE:ReflectionParser>"
                "${_swReflectBuiltins}" "${_swAnnotationMeta}" ${_swEmitTpls}
                ${_swParserConfigs}
        COMMENT "[Reflection] Running ReflectionParser for target: ${TARGET_NAME}"
        VERBATIM
    )

    set(generatedCppFiles "")
    foreach(header IN LISTS ARG_HEADERS)
        get_filename_component(stem "${header}" NAME_WE)
        list(APPEND generatedCppFiles "${ARG_OUTPUT_DIR}/${stem}.gen.cpp")
    endforeach()

    target_sources(${TARGET_NAME} PRIVATE ${generatedCppFiles})
    set_source_files_properties(${generatedCppFiles} PROPERTIES SKIP_UNITY_BUILD_INCLUSION ON)
    target_include_directories(${TARGET_NAME} PUBLIC "${ARG_OUTPUT_DIR}")

    set(_swHasFlagEnum FALSE)
    foreach(header IN LISTS ARG_HEADERS)
        if(EXISTS "${header}")
            file(STRINGS "${header}" _swFlagLines LIMIT_COUNT 1 REGEX "^[ \t]*ENUM[ \t]*\\([ \t]*Flags")
            if(_swFlagLines)
                set(_swHasFlagEnum TRUE)
                break()
            endif()
        endif()
    endforeach()
    if(_swHasFlagEnum)
        if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
            target_compile_options(${TARGET_NAME} PUBLIC "/FI${_swFlagOpsHeader}")
        else()
            target_compile_options(${TARGET_NAME} PUBLIC "SHELL:-include ${_swFlagOpsHeader}")
        endif()
    endif()

    add_custom_target(${TARGET_NAME}_ReflectionGen DEPENDS ${generatedFiles})
    add_dependencies(${TARGET_NAME} ReflectionParser ${TARGET_NAME}_ReflectionGen)

    message(STATUS "[Reflection] Parser step registered for target: ${TARGET_NAME}")
    message(STATUS "[Reflection] Output directory: ${ARG_OUTPUT_DIR}")
endfunction()

# ------------------------------------------------------------------------------
# 2) sw_addReflectBuiltinsGen — ReflectBuiltins.h → TypeRegistrar .gen.cpp
#    Engine 전용. Unity 배치에서 제외
# ------------------------------------------------------------------------------
function(sw_addReflectBuiltinsGen TARGET_NAME)
    if(NOT TARGET ReflectionParser)
        if(SW_REQUIRE_REFLECTION)
            message(FATAL_ERROR "[Reflection] ReflectionParser missing for builtins gen (${TARGET_NAME}).")
        endif()
        message(WARNING "[Reflection] Skipping ReflectBuiltins.gen.cpp for: ${TARGET_NAME}")
        return()
    endif()

    set(_swReflectBuiltins "${CMAKE_SOURCE_DIR}/${SW_FILE_REFLECT_BUILTINS}")
    set(_swEmitTemplatesDir "${CMAKE_SOURCE_DIR}/${SW_DIR_TOOLS_REFLECTION_TEMPLATES}")
    file(GLOB _swBuiltinTpls
        "${_swEmitTemplatesDir}/${SW_FILE_TPL_BUILTIN_HEADER}"
        "${_swEmitTemplatesDir}/${SW_FILE_TPL_BUILTIN_REGISTRAR}"
        "${_swEmitTemplatesDir}/${SW_FILE_TPL_BUILTIN_FOOTER}")
    set(_outDir "${CMAKE_BINARY_DIR}/generated/${TARGET_NAME}")
    set(_genFile "${_outDir}/ReflectBuiltins.gen.cpp")
    file(MAKE_DIRECTORY "${_outDir}")
    if(NOT EXISTS "${_genFile}")
        file(WRITE "${_genFile}" "// AUTO-GENERATED placeholder — regenerated by ReflectionParser\n")
    endif()

    add_custom_command(
        OUTPUT "${_genFile}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${_outDir}"
        COMMAND "$<TARGET_FILE:ReflectionParser>"
                "--builtins" "${_swReflectBuiltins}"
                "--emit-templates" "${_swEmitTemplatesDir}"
                "--emit-builtins-gen" "${_genFile}"
        DEPENDS ReflectionParser "${_swReflectBuiltins}" ${_swBuiltinTpls}
        COMMENT "[Reflection] Emitting ReflectBuiltins.gen.cpp for ${TARGET_NAME}"
        VERBATIM
    )

    target_sources(${TARGET_NAME} PRIVATE "${_genFile}")
    set_source_files_properties("${_genFile}" PROPERTIES SKIP_UNITY_BUILD_INCLUSION ON)
    target_include_directories(${TARGET_NAME} PRIVATE "${_outDir}")
    add_dependencies(${TARGET_NAME} ReflectionParser)
    message(STATUS "[Reflection] Builtins TypeRegistrar gen → ${_genFile}")
endfunction()
